module.exports = [
    {
      advisorOwner: "John Doe",
      firstName: "Jane",
      lastName: "Smith",
      mobile: "123-456-7890",
      email: "jane.smith@example.com",
      landline: "987-654-3210",
      location: "New York",
      leadSource: "Referral",
      advisorsLicenceNumber: "LIC123456",
      Whatsapp: "+11234567890",
      AppAdvisorID: "APPID7890",
      ciprNumber: "CIPR001234",
      vendor: "InsuranceCorp",
      AdvisorsDateofBirth: "1985-05-20",
      Reviewedason: "2024-01-15",
      assignedAdvisor: "Agent X",
      cessationDate: "2024-06-30",
      hireDate: "2023-01-01",
      appAdvisorID: "APP7890",
      myCalendar: "https://calendar.example.com/janesmith",
      status: "Active",
      exchangeRate: "1.15",
      eoPolicyNumber: "EOP-987654",
      AdditionalContactInformation: "N/A",
      isSocial: "Yes",
      inactiveAdvisor: "No",
      emailOptOut: "No",
      removeFromCampaign: "Yes",
      organizationLevel: "Senior",
      insuranceAdvisor: "Yes",
      teamName: "Alpha Team",
      teamLeg: "A",
      employmentType: "Full-time",
      insurancePartner: "Life Insurance Inc.",
      reviewedDate: "2024-01-15",
      generationNumber: 1,
      hireLevel: "Level 3",
      hireType: "New Hire",
      hireTeamName: "Bravo Team",
      hireTeamLeg: "B",
      teamGenerationNumber: 2,
      lifeCareerPreferences: "Career Growth",
      desiredTimeline: "2025-12-31",
      bonusLevel: "High",
      fycPercentage: "15%",
      supervisaPayout: "Standard",
      premiumPercentage: "10%",
      Description: "Top advisor in the region",
      catalystId: "CAT1234",
      bestTimeToCall: "Afternoon",
      location2: "California",
      referralNameClient: "Referral Client A",
      preferredContact: "Email",
      preferredContactTime: "Morning",
      isthisaReassignment: "No",
      loanProtection: "Yes",
      socialMediaInfo: "LinkedIn, Twitter",
      groupInsurance: "Yes",
      referredBy: "David Brown",
      refbyAdvisor: "External Referral - John Doe",
      citizenshipStatus: "Permanent Resident",
      understandingOfInsurance: "Advanced",
      existingInsurancePolicy: "Yes",
      serviceRequested: "Life Insurance",
      doYouOwnHomeInCanada: "Yes",
      existingPolicyRenewalDueBy: "2024-12-01",
      doYouHaveLifeInsurance: "Yes",
      productCataegory: "Life Insurance",
      submitPageUrl: "http://example.com/submit",
      assignedCampaigns: "Campaign A, Campaign B",
      potentialBusiness: "500000",
      insuranceLeadScoringPositiveScore: "85",
      insuranceLeadsScoringTouchPointScore: "90",
      insuranceLeadScoringNegativeScore: "-10",
      insuranceLeadScoringScore: "80",
      insuranceLeadPositiveTouchScoringScore: "75",
      insuranceLeadNegativeTouchScoringScore: "-5",
      coverageLokkingFor: "Comprehensive",
      gender: "Female",
      addContactInfo: "Prefers text messages",
      netWorth: "750000",
      genderprediction: "Female",
      currency: "USD",
      roundRobinAssignmentTime: "2024-01-10T09:00:00Z",
      nextFollowUpDateTime: "2024-02-15T15:00:00Z",
      leadCreatedOn: "2024-01-01",
      oldLeadDatabase: "No",
      emailIsValid: "Yes",
      combinationHybird: "Yes",
      roundRobinProcessed1: "Yes",
      emailRoundRobinOwner2: "No",
      eligibleRoundRobinOwnerFound1: "Yes",
      rerunroundrobin: "No",
      healthAndDentalInsurance: "Yes",
      rCSMSOptOut: "No",
      adAccount: "AdAcc1234",
      adAccountId: "AdAccID5678",
      fbAdInfo: "High Engagement",
      adCampaign: "Campaign 2024",
      adCampaignId: "CampID2024",
      faceBookPage: "Insurance Advisors",
      faceBookPageId: "FBPageID123",
      costPerLead: "20",
      adSet: "AdSetA",
      adSetId: "AdSetID789",
      facebookAd: "Ad #5",
      adId: "AdID123",
      leadForm: "Form A",
      leadFormId: "FormID456",
      skypeID: "jane.smith.skype",
      instagramID: "@jane_smith",
      linkedinID: "jane-smith-profile",
      twitterID: "@JaneSmithAdvisors",
      investment: "50000",
      lifeInsurance: "Term Life",
      lifeBenefit: "Accidental Death Benefit",
      travelInsurance: "Yes",
      facebook: "Jane Smith",
      twitter: "@JaneSmithAdvisors",
      linkedin: "Jane Smith",
      googleReview: "4.8",
      youtubeVedio: "Introduction to Life Insurance",
      Mailingstreet: "123 Main St",
      Mailingcity: "New York",
      MailingState: "NY",
      MailingpostalCode: "10001",
      Mailingcountry: "USA",
      street: "456 Elm St",
      city: "Los Angeles",
      State: "CA",
      postalCode: "90001",
      country: "USA",
      relationShipStatus: "Married",
      nameOfSpouse: "John Smith",
      numberOfSpouse: "1",
      anniversaryDate: "2010-05-15",
      spouseDateOfBirth: "1982-10-25",
      phoneOfSpouse: "321-654-9870",
      emailOfSpouse: "john.smith@example.com",
      nameOfCommonLawPartner: "",
      commonLawDateOfBirth: "",
      dependentParents: "No",
      numberOfDependentParents: 0,
      dependentChildren: "Yes",
      numberOfDependentChildren: 2,
      siblings: "Yes",
      numberOfSiblings: 1,
      emergencyContactData: "Mary Johnson, 555-123-4567, Sister, mary.johnson@example.com",
      AdvisorFyc: "2023, 10000",
      advisorBonus: "2023, 2000",
      religion: "Christian",
      celebratedFestivals: "Christmas, Easter",
      festivalsData: "Christmas, 2024-12-25"
    }
  ];