export const statusOptions = [
  { label: "-None-", value: "-None-", color: "#9e9e9e" },
  { label: "Not Started", value: "Not Started", color: "#fd8989" },
  { label: "No Response-Client", value: "No Response-Client", color: "#eb4d4d" },
  { label: "Open", value: "Open", color: "#5cb3fd" },
  { label: "in Progress", value: "in Progress", color: "#c4f0b3" },
  { label: "Closed", value: "Closed", color: "#25b52a" },
];
export const ServiceStatusOptions = [
  { label: "-None-", value: "-None-", color: "#9e9e9e" },
  { label: "Yes", value: "Yes", color: "#25b52a" },
  { label: "No", value: "No", color: "#eb4d4d" },
  { label: "Not Started", value: "Not Started", color: "#fea36a" },
  { label: "Not Applicable" ,value:"Started", color: "#ffc6c6" },
];

export const TaskTypeOptions = [
  { label: "15 Days Effective Date Reminder Task", value: "15 Days Effective Date Reminder Task", color: "#fd8989" },
  { label: "3 Days Effective Date Reminder Task", value: "3 Days Effective Date Reminder Task", color: "#25b52a" },
  { label: "30 Days Effective Date Reminder Task", value: "30 Days Effective Date Reminder Task", color: "#c4f0b3" },
  { label: "7 Days Effective Date Reminder Task", value: "7 Days Effective Date Reminder Task", color: "#ced9ff" },
  { label: "Address Update", value: "Address Update", color: "#9a2e47" },
  { label: "Cancellation - Client Reqest", value: "Cancellation - Client Reqest", color: "#c9651a" },
  { label: "Cancellation - Client's request", value: "Cancellation - Client's request", color: "#c9ba46" },
  { label: "Card Update", value: "Card Update", color: "#9a2e47" },
  { label: "Contact Information(Email Change)", value: "Contact Information(Email Change)", color: "#fd8989" },
  { label: "Contact Information(Home Address Change)", value: "Contact Information(Home Address Change)", color: "#f6c1ff" },
  { label: "Contact Information(Mobile Change)", value: "Contact Information(Mobile Change)", color: "#ffc6c6" },
  { label: "Coverage Change", value: "Coverage Change", color: "#fd8989" },
  { label: "Date Change", value: "Date Change", color: "#af38fa" },
  { label: "Deductible Change", value: "Deductible Change", color: "#90a9fd" },
  { label: "Early Return Cancellation", value: "Early Return Cancellation", color: "#98d681" },
  { label: "Health Card", value: "Health Card", color: "#e972fd" },
  { label: "Insured Details Amendment", value: "Insured Details Amendment", color: "#ffc6c6" },
  { label: "MD form- Zoho Sign", value: "MD form- Zoho Sign", color: "#8a37be" },
  { label: "Monthly Payment Failed", value: "Monthly Payment Failed", color: "#af38fa" },
  { label: "No Renewal Needed", value: "No Renewal Needed", color: "#f6c1ff" },
  { label: "OHIP Cancellation", value: "OHIP Cancellation", color: "#616e88" },
  { label: "Other", value: "Other", color: "#ced9ff" },
  { label: "Pending Renewal", value: "Pending Renewal", color: "#f5c72f" },
  { label: "Phone Number/ Email Update", value: "Phone Number/ Email Update", color: "#c9651a" },
  { label: "Phone number/Email Update", value: "Phone number/Email Update", color: "#8a37be" },
  { label: "Premium Change", value: "Premium Change", color: "#c9ba46" },
  { label: "Related policy issued - Cancellation", value: "Related policy issued - Cancellation", color: "#25b52a" },
  { label: "Related Policy Issued- Cancellation", value: "Related Policy Issued- Cancellation", color: "#ced9ff" },
  { label: "Renewal", value: "Renewal", color: "#c4f0b3" },
  { label: "Visa Decline Cancellation", value: "Visa Decline Cancellation", color: "#177ba0" },
];
