module.exports = {
    "Looking For Advisor?":"LookingForAdvisor",
    "What time frame you like to move to be a advisor?":"whatTimeFrameYouLikeToMoveToBeaAdvisor	",
    "Lead ID":"leadId",
    "Type Of Insurance Looking":"typeOfInsuranceLooking",
    "What Policy Do You Want":"whatPolicyDoYouWant",
    "Age Of 1st Traveler":"ageOf1stTraveler",
    "Enterage Of 2nd Traveler":"enterageOf2ndTraveler",
    "Traveler Start Date":"travelerStartDate",
    "Traveler End Date":"travelerEndDate",
    "Coverage You Are Looking For":"coverageYouAreLookingFor",
    "Pre Existing Medical Conditions":"preExistingmedicaLconditions",
    "How Much Coverage Is Required":"howMuchCoverageIsRequired",
    "Can You Please Let Me Know Premium Payment Mode":"canYouPleaseLetMeKnowPremiumPaymentMode",
    "Tobacco Used":"tobaccoused",
    "What Type Of Term Plan Are You Looking For":"whatTypeOfTermPlanAreYouLookingFor",
    "Do You Want Critical Illness Insurance With Money":"doYouWantCriticalIllnessInsuranceWithMoney",
    "How Do You Consider Your Health":"howDoYouConsiderYourHealth",
    "Whats Your Profession":"whatsYourProfession",
    "How Many Critical Illness Coverage You Need":"howManyCriticalIllnessCoverageYouNeed",
    "How Much Monthly Benefit Do You Need":"howMuchMonthlyBenefitDoYouNeed",
    "Select The Duration Of The Coverage":"selectTheDurationOfTheCoverage",
    "You Are Seeking CoverageFor":"youAreSeekingCoverageFor",
    "Enter The Amount Of Mortgage Coverage Required":"enterTheAmountOfMortgageCoverageRequired",
    "Whats Your Age":"whatsYourAge",
    "Do You Have Any Medical Issue":"doYouHaveAnyMedicalIssue",
    "Resp Accounts For Your Child Childrens":"respAccountsForYourChildChildrens",
    "Secure Your Childs Future With Higher Education":"secureYourChildsFutureWithHigherEducation",
    "How Much Do You Want To Save Monthly":"howMuchDoYouWantToSaveMonthly",
    "Growth On Your Investment In Resp Account":"growthOnYourInvestmentInRespAccount",
    "Would Like To Increase Monthly Deposits":"wouldLikeToIncreaseMonthlyDeposits",
    "Qualify For 15 Bonus Of Your Resp Account":"qualifyFor15BonusOfYourRespAccount",
    "How Many Childrens Do You Have":"howManyChildrensDoYouHave",
    "Eligible To Get Extra 2000 In Government Grants":"eligibleToGetExtra2000InGovernmentGrants",
    "What Is Your Residency Status In Canada":"whatIsYourResidencyStatusInCanada",
    "Deposit Every Month Towards Your Child Education":"depositEveryMonthTowardsYourChildEducation",
    "How Long Do You Need Coverage For":"howLongDoYouNeedCoverageFor",
    "Would You Like To Know How Resp Works":"wouldYouLikeToKnowHowRespWorks",
    "Money Require To Complete Your Childs Education":"moneyRequireToCompleteYourChildsEducation",
    "Select Your Age Bracket":"selectYourAgeBracket",
    "One Million Inan Resp Account At Retirement":"oneMillionInanRespAccountAtRetirement",
    "How Much Do You Want To Save Yearly":"howMuchdoYouWantToSaveYearly",
    "Do You Wan To Deposit Monthly Or Yearly Premium":"doYouWanToDepositMonthlyOrYearlyPremium",
    "Would You Like To Know How Tfsa Works":"wouldYouLikeToKnowHowTfsaWorks",
    "What Age Do You Want To Start The Withdrawal From":"whatageDoYouWanttostartTheWithdrawalFrom",
    "What Kind Of Businesss Is It":"whatKindOfBusinesssIsIt",
    "Would You Like To Know How Rrsp Works":"wouldYouLikeToKnowHowRrspWorks",
    "One Million In An Tfsa Account At Retirement":"oneMillionInAnTfsaAccountAtRetirement",
    "Are You An Owner Or Employee Of The Business":"areYouAnOwnerOrEmployeeOfTheBusiness",
    "Gcl Id Field":"gclidField",
    "Are You Looking For Drug And Dental Or Just Drug Pla":"areYouLookingForDrugAndDentalOrJustDrugPla",
    "Are You Licensed As An Insurance Advisor":"areYouLicensedAsAnInsuranceAdvisor",
    "Would You Like To Know How Super Visa Insurance Wo":"wouldYouLikeToKnowHowSuperVisaInsuranceWo",
    "Existing Health Conditions":"existingHealthConditions",
    "Single Or Family Plan":"singleOrFamilyPlan",
    "Monthly Premium Knowledge":"monthlyPremiumKnowledge",
    "Previous Policy With Us":"previousPolicyWithUs",
    "Coverage For Drug And Dental Cost":"coverageForDrugAndDentalCost",
    "Prescription Medication Coverage":"prescriptionMedicationCoverage",
    "Super Visa Insurance":"superVisaInsurance",
    "Secure Your Child Future With Higher Education":"secureYourChildFutureWithHigherEducation",
    "Money Require To Complete Your Child Education":"moneyRequireToCompleteYourChildEducation",
    "Total Dependents":"totalDependents",
    "Dependent Age 1":"dependentAge1",
    "Dependent Age 2":"dependentAge2",
    "Dependent Age 3":"dependentAge3",
    "Dependent Age 4":"dependentAge4",
    "Dependent Age 5":"dependentAge5",
    "Dependent Age 6":"dependentAge6"
};    
