module.exports = {
    "Lead ID":"leadID",
    "First Name":"firstName",
    "Last Name":"lastName",
    "Email":"email",
    "Secondary Email":"secondaryEmail",
    "Currency":"currency",	
    "Exchange Rate":"exchangeRate",
    "Email Opt Out":"emailOptOut",
    "Mobile":"mobile",
    "Lead Source":"insuranceLeadSource",
    "Lead Status":"leadStatus",
    "Postal Code":"whatIsYourPostalCode",
    "Description":"description",
    "Insurance Lead Owner":"insuranceLeadOwner",
    "Insurance Lead Status":"insuranceLeadStatus",
    "Whatsapp":"whatsapp",
    "Lead Status Stage":"leadStatusStage",
    "Assigned Advisor":"assignedAdvisor",
    "Email Is Valid":"emailIsValid",
    "Remove From Campaign":"removeFromCampaign",
    "Date Of Birth":"dateOfBirth",
    "Best Time To Call":"bestTimeToCall",
    "Gender":"gender",
    "Is This a Reassignment":"isThisaReassignment",
    "Location Name":"locationName",
    "Referred By":"referredBy",
    "Net Worth":"netWorth",
    "Preferred Contact Method":"preferredContactMethod",
    "Preferred Contact Time":"preferredContactTime",
    "Social Media Information":"socialMediaInformation",
    "Round Robin Processed":"roundRobinProcessed",
    "Citizenship Status":"citizenshipStatus",
    "Email Round Robin Owner":"emailRoundRobinOwner",
    "Understanding Of Insurance":"understandingOfInsurance",
    "Existing Insurance Policy":"existingInsurancePolicy",
    "Eligible Round Robin Owner Found":"eligibleRoundRobinOwnerFound",
    "Do You Own a Home In Canada":"doYouOwnaHomeInCanada",
    "Do You have Life Insurance":"doYouhaveLifeInsurance",
    "Old Database Lead":"oldDatabaseLead",
    "Next Follow Up Date Time":"nextFollowUpDateTime",
    "Gender Prediction Score":"genderPredictionScore",
    "Re Run Round Robin":"reRunRoundRobin",
    "Rc Sms Opt Out":"rcSmsOptOut",
    "Submit Page URL":"submitPageURL",
    "Are You Ready To Purchase This Life Insurance Poli":"areYouReadyToPurchaseThisLifeInsurancePoli",
    "Assigned Campaigns":"assignedCampaigns",
    "Are You Ready To Purchase This Life Insurance Pol":"areYouReadyToPurchaseThisLifeInsurancePol",
    "Gender Prediction":"genderPrediction",
    "Inbox URL":"inboxURL",
    "Additional Contact Information":"additionalContactInformation",
    "AreYouLLQPLicensed":"areYouLLQPLicensed",
    "Phone Burner Follow UpDate":"phoneBurnerFollowUpDate",
    "Phone Burner Last Call Outcome":"phoneBurnerLastCallOutcome",
    "Phone Burner Last Call Time":"phoneBurnerLastCallTime",
    "Driver License No":"driverLicenseNo",
    "Vehicle Year":"vehicleYear",
    "When Was Your Vehicle Made":"whenWasYourVehicleMade",
    "Phone Number":"phoneNumber",
    "Name":"name",
    "Add Email 1":"addEmail1",
    "Quote":"quote",
    "Deposit":"deposit",
    "Date Of Birth 1":"dateOfBirth1",
    "Child Age":"childAge",
    "How Much You Like To Start The Plan":"howMuchYouLikeToStartThePlan",
    "How Much Amount Want To Start With":"howMuchAmountWantToStartWith",
    "Date Of Birth Of Traveler":"dateOfBirthOfTraveler",
    "Religion":"religion",
    "Celebrated Festivals":"celebratedFestivals",
    "Round Robin Assignment Time":"roundRobinAssignmentTime",
    "Layout Name":"layoutName",
    "Source Id":"sourceId",
    "Source":"source",
    "Where Would You Be Travellingto":"whereWouldYouBeTravellingto",
    "What type of Student":"whattypeofStudent",
    "Trip Type":"tripType",
    "Start Date Of Coverage":"startDateOfCoverage",
    "If Referred By Advisor Or External Referral":"ifReferredByAdvisorOrExternalReferral",
    "Existing Policy Renewal Due By":"existingPolicyRenewalDueBy",
    "Coverage You Are Looking For":"coverageYouAreLookingFor",
    "Fax":"fax",
    "Ready For Purchase":"readyForPurchase",
    "Lead Created On":"leadCreatedOn",
    "Lead Referral Id":"leadReferralId"
};    
