module.exports = {
    "Street Address":"street",
    "City":"city",
    "Lead ID":"leadId",
    "Contact":"contact",
    "Contact Id":"contactId",
    "Best Time To Call":"bestTimeToCall",
    "Date Of Birth 1":"dateOfBirth1",
    "If Referred By Advisor":"ifreferredbyAdvisor",
    "Is This A Reassignment":"isthisAReassignment",
    "Referred By":"referredBy",
    "Investments1":"investments1",
    "Preferred Contact Method2":"preferredContactMethod2",
    "Preferred Contact Time2":"preferredContactTime2",
    "Citizenship Status1":"citizenshipStatus1",
    "Understanding Of Insurance1":"understandingOfInsurance1",
    "Existing Insurance Policy2":"existingInsurancePolicy2",
    "Do You Own A Home In Canada":"doYouOwnAHomeInCanada",
    "Existing Policy Renewal Due By":"existingPolicyRenewalDueBy",
    "Do You Have Life Insurance":"doYouHavelifeInsurance",
    "Submit Page Url":"submitPageUrl",
    "Country":"country",
    "Assigned Campaigns":"assignedCampaigns",
    "State":"state",
    "Linked In1":"linkedIn1",
    "Zip Code":"zipCode",
    "Facebook Ad Information":"facebookAdInformation",
    "Twitter1":"twitter1",
    "Services Requested":"servicesRequested",
    "Skype Id":"skypeId",
    "Instagram1":"instagram1",
    "Insurence Leads Scoring Positive Touch Point Score":"insurenceLeadsScoringPositiveTouchPointScore",
    "Insurence Leads Scoring Negative Score":"insurenceLeadsScoringNegativeScore",
    "Insurance Leads Scoring Score":"insuranceLeadsScoringScore",
    "Insurence Leads Scoring Positive Score":"insurenceLeadsScoringPositiveScore",
    "Insurence Leads Scoring Negative Touch Point Score":"insurenceLeadsScoringNegativeTouchPointScore",
    "Coverage You Are Looking For":"coverageYouAreLookingFor",
    "Insurance Lead Scoring Positive Score":"insuranceLeadScoringPositiveScore",
    "Insurance Lead Scoring Negative Touch Point Score":"insuranceLeadScoringNegativeTouchPointScore",
    "Gender1":"gender1",
    "Additional Contact Information":"additionalContactInformation",
    "Networth2":"networth2",
    "Database Lead1":"databaseLead1",
    "Gender Prediction1":"genderPrediction1",
    "Exchange Rate1":"exchangeRate1",
    "Currency1":"currency1",
    "Lead Created On1":"leadCreatedOn1",
    "Linkdin1":"linkdin1",
    "FaceBook":"faceBook",
    "Insurance Lead Scoring Touch Point Score":"insuranceLeadScoringTouchPointScore",
    "Insurance Lead Scoring Positive Touch Point Score":"insuranceLeadScoringPositiveTouchPointScore",
    "Insurance Lead Scoring Negative Score":"insuranceLeadScoringNegativeScore",
    "Old Database Lead1":"oldDatabaseLead1",
    "Ad Account":"adAccount",
    "Ad Set":"adSet",
    "Ad Campaign":"adCampaign",
    "Facebook Ad":"facebookAd",
    "Ad Id":"adId",
    "Facebook Page":"facebookPage",
    "Lead Form":"leadForm",
    "Ad Account Id":"adAccountId",
    "Ad Set Id":"adSetId",
    "Ad Campaign Id":"adCampaignId",
    "Facebook Page Id":"facebookPageId",
    "Lead Form Id":"leadFormId",
    "Cost Per Lead":"costPerLead",
    "Instagram Id":"instagramId",
    "Year":"year",
    "Referral Client":"referralClient",
    "Referral Source":"referralSource",
    "Referral Other Than Client":"referralOtherThanClient",
    "Product Category Referred":"productCategoryReferred",
    "If Referred By Advisor Or External":"ifReferredByAdvisorOrExternal",
    "Existing Renewal Policy Due By":"existingRenewalPolicyDueBy",
    "Skype Id1":"skypeId1",
    "Round Robin Assignment Time1":"roundRobinAssignmentTime1",
    "Lead Potential Business Policy Values":"leadPotentialBusinessPolicyValues",
    "Insurance Lead Score":"insuranceLeadScore",
    "Facebook1":"facebook1",
    "Insurance Leads Scoring Positive Touch Point Score":"insuranceLeadsScoringPositiveTouchPointScore",
    "Insurance Leads Scoring Negative Score":"insuranceLeadsScoringNegativeScore",
    "Whatsapp":"whatsapp",
    "Phone Burner Last Outcome":"phoneBurnerLastOutcome",
    "Catalyst Id":"catalystId",
    "Is This Reassignment":"isThisReassignment",
    "Do You Own Home In Cananda":"doYouOwnHomeInCananda",
    "Additional Contact Information1":"additionalContactInformation1",
    "Lead Info Additional Contact Information":"leadInfoAdditionalContactInformation",
    "Home Insurance":"homeInsurance",
    "Location Name2":"locationName2"
};    
