module.exports = {
    "Potential Business":"potentialBusiness",
    "Loan Protection":"loanProtection",
    "Lead ID":"leadId",
    "Services Requested":"servicesRequested",
    "Life Insurance":"lifeInsurance",
    "Investments":"investments",
    "Living Benefits":"livingBenefits",
    "Group Insurance":"groupInsurance",
    "Travel Insurance":"travelInsurance",
    "Combination Or Hybrid Insurance":"combinationOrHybridInsurance",
    "Auto Insurance":"autoInsurance",
    "Health And Dental Insurance":"healthAndDentalInsurance",
    "Home Insurance":"homeInsurance",
    "Business Liability Insurance":"businessLiabilityInsurance",
    "Immigration Services":"immigrationServices",
    "Campaign Id Data":"campaignidData",
    "Network Data":"networkData",
    "Ad Group Id Data":"adgroupidData",
    "Device Data":"deviceData",
    "Match Type Data":"matchtypeData",
    "Keyword Data":"keywordData",
    "Gcl Id Data":"gclidData",
    "Lp Url Data":"lpUrlData"
};    
