import { Download, Trash2 } from "lucide-react";
import VendorList from "../finance/pages/vendors/VendorsList";

export const moreOptions = [
  {
    label: "Import",
    icon: <Trash2 size={16} />,
    action: () => console.log("Delete clicked"),
  },
  {
    label: "Export",
    icon: <Download size={16} />,
    action: () => console.log("Export clicked"),
  },
];

export const leadSource = [
  { label: "Advertisement", value: "advertisement" },
  { label: "Answering Service", value: "answering-service" },
  { label: "AOL", value: "aol" },
  { label: "Ask.com", value: "ask.com" },
  { label: "Bing Ads", value: "bing-ads" },
  { label: "Bing Search Engine", value: "bing-search-engine" },
  { label: "Direct", value: "direct" },
  { label: "Google", value: "google" },
  { label: "Marketing", value: "marketing" },
  { label: "Other", value: "other" },
  { label: "Outbound", value: "outbound" },
  { label: "Partner", value: "partner" },
  { label: "Public Relations", value: "public-relations" },
  { label: "Referral", value: "referral" },
  { label: "Search Engine", value: "search-engine" },
  { label: "Social Media", value: "social-media" },
  { label: "Unknown", value: "unknown" },
  { label: "Web", value: "web" },
];

export const dealSource = leadSource;


export const leadStatus = [
  { label: "New Lead", value: "new-lead" },
  { label: "Attempted to Contact", value: "attempted-to-contact" },
  { label: "Contacted", value: "contacted" },
  { label: "Contact in Future", value: "contact-in-future" },
  { label: "Not Contacted", value: "not-contacted" },
  { label: "Lost Lead", value: "lost-lead" },
  { label: "Junk Lead", value: "junk-lead" },
  { label: "Not Qualified", value: "not-qualified" },
  { label: "Nurturing", value: "nurturing" },
  { label: "Convert to Deal", value: "convert-to-deal" },
];

export const leadOwner = [
  { label: "Pappu", value: "22106000006168768" },
  { label: "Jamik Tashpulatov", value: "jamik-tashpulatov" },
  { label: "Emily Whalen", value: "emily-whalen" },
  { label: "Sophia Martinez", value: "sophia-martinez" },
  { label: "Maya Johnson", value: "maya-johnson" },
  { label: "Carlos Rodriguez", value: "carlos-rodriguez" },
  { label: "Emma Davis", value: "emma-davis" },
  { label: "Leila Ahmadi", value: "leila-ahmadi" },
  { label: "Thomas Wilson", value: "thomas-wilson" },
  { label: "Daniel Park", value: "daniel-park" },
  { label: "Michael Chen", value: "michael-chen" },
  { label: "Sophia Martinez", value: "sophia-martinez" },
  { label: "Maya Johnson", value: "maya-johnson" },
  { label: "Carlos Rodriguez", value: "carlos-rodriguez" },
  { label: "Emma Davis", value: "emma-davis" },
  { label: "Leila Ahmadi", value: "leila-ahmadi" },
  { label: "Thomas Wilson", value: "thomas-wilson" },
];

export const dealOwner = [
  { label: "Pappu", value: "22106000006168768" },
  { label: "Jamik Tashpulatov", value: "jamik-tashpulatov" },
  { label: "Emily Whalen", value: "emily-whalen" },
  { label: "Sophia Martinez", value: "sophia-martinez" },
  { label: "Maya Johnson", value: "maya-johnson" },
  { label: "Carlos Rodriguez", value: "carlos-rodriguez" },
  { label: "Emma Davis", value: "emma-davis" },
  { label: "Leila Ahmadi", value: "leila-ahmadi" },
  { label: "Thomas Wilson", value: "thomas-wilson" },
  { label: "Daniel Park", value: "daniel-park" },
  { label: "Michael Chen", value: "michael-chen" },
  { label: "Sophia Martinez", value: "sophia-martinez" },
  { label: "Maya Johnson", value: "maya-johnson" },
  { label: "Carlos Rodriguez", value: "carlos-rodriguez" },
  { label: "Emma Davis", value: "emma-davis" },
  { label: "Leila Ahmadi", value: "leila-ahmadi" },
  { label: "Thomas Wilson", value: "thomas-wilson" },
];

export const industry = [
  { label: "Abrasive Products", value: "abrasive-products" },
  { label: "Adhesives Sealants", value: "adhesives-&-sealants" },
  { label: "Aerospace Industries", value: "aerospace-industries" },
  { label: "Air Gas Compressors", value: "air-&-gas-compressors" },
  {
    label: "Air Conditioning Supplies Parts Mfrs",
    value: "air-conditioning-supplies-&-parts-mfrs",
  },
  {
    label: "Aircraft Equipment Parts Supls Mfrs",
    value: "aircraft-equipment-parts-&-supls-mfrs",
  },
  {
    label: "Alternators Generators Automotive Mfrs",
    value: "alternators-&-generators-automotive-mfrs",
  },
  { label: "Aluminum Fabricators", value: "aluminum-fabricators" },
  {
    label: "Appliances Household Major Manufacturers",
    value: "appliances-household-major-manufacturers",
  },
];

export const city = [
  { label: "Abbeville", value: "abbeville" },
  { label: "Abbotsford", value: "abbotsford" },
  { label: "Abbott", value: "abbott" },
  { label: "Abbottsford", value: "abbottsford" },
  { label: "Abbyville", value: "abbyville" },
  { label: "Abell", value: "abell" },
  { label: "Abilene", value: "abilene" },
  { label: "Abingdon", value: "abingdon" },
];

export const state = [
  { label: "Alabama", value: "alabama" },
  { label: "Alaska", value: "alaska" },
  { label: "Albemarle", value: "albemarle" },
  { label: "Alberta", value: "alberta" },
  { label: "Albany", value: "albany" },
  { label: "Albany", value: "albany" },
  { label: "Alcona", value: "alcona" },
  { label: "Alden", value: "alden" },
  { label: "Aledo", value: "aledo" },
  { label: "Aleknagik", value: "aleknagik" },
  { label: "Alexander", value: "alexander" },
  { label: "Alexandria", value: "alexandria" },
  { label: "Alger", value: "alger" },
  { label: "Allegan", value: "allegan" },
  { label: "Allegany", value: "allegany" },
  { label: "Alleghany", value: "alleghany" },
  { label: "Allegheny", value: "allegheny" },
  { label: "Allen", value: "allen" },
  { label: "Allendale", value: "allendale" },
];

export const pipeline = [
  { label: "B2B", value: "b2b" },
  { label: "B2C", value: "b2c" },
];

export const currecy = [
  { label: "USD", value: "usd" },
  { label: "EUR", value: "eur" },
  { label: "GBP", value: "gbp" },
  { label: "JPY", value: "jpy" },
  { label: "CAD", value: "cad" },
  { label: "AUD", value: "aud" },
  { label: "NZD", value: "nzd" },
  { label: "CHF", value: "chf" },
  { label: "SEK", value: "sek" },
  { label: "DKK", value: "dkk" },
  { label: "NOK", value: "nok" },
  { label: "HKD", value: "hkd" },
  { label: "SGD", value: "sgd" },
  { label: "INR", value: "inr" },
  { label: "KWD", value: "kwd" },
];


// export const accountType = [
//   { label: "Account Type", value: "account-type" },
//   { label: "Consultant", value: "consultant" },
//   { label: "Owner", value: "owner" },
//   { label: "Main Contractor", value: "main-contractor" },
//   { label: "Applicator", value: "applicator" },
//   { label: "Retailer", value: "retailer" },
// ];
export const accountType = [
  { label: "Owner/Developer", value: "owner-developer" },
  { label: "Civil Contractor", value: "civil-contractor" },
  { label: "MEP Contractor", value: "mep-contractor" },
  { label: "Applicator", value: "applicator" },
  { label: "Retail", value: "retail" },
  { label: "Consultant", value: "consultant" },
  { label: "Sub-Contractor", value: "sub-contractor" },
  // { label: "Aluminum & Glass Customers", value: "aluminum-glass-customers" },

];
export const accountOptions = [
  { value: "TrigyaInnovation", label: "Trigya Innovation Pvt Ltd" },
  { value: "BetaCorp", label: "Beta Corporation" },
  { value: "GammaLtd", label: "Gamma Limited" }
];
export const segment=[
  {label:"retail", value:"retail"},
  {label:"project", value:"project"},
];
// constants.js
export const partyTypes = [
  { label: "Owner/Developer", value: "owner-developer" },
  { label: "Civil Contractor", value: "civil-contractor" },
  { label: "MEP Contractor", value: "mep-contractor" },
  { label: "Applicator", value: "applicator" },
  { label: "Retail", value: "retail" },
  { label: "Consultant", value: "consultant" },
  { label: "Sub-Contractor", value: "sub-contractor" },
  { label: "Aluminum & Glass Customers", value: "aluminum-glass-customers" },
];

export const company = [
  { label: "Owner/Developer", value: "owner-developer" },
  { label: "Civil Contractor", value: "civil-contractor" },
  { label: "MEP Contractor", value: "mep-contractor" },
  { label: "Applicator", value: "applicator" },
  { label: "Retail", value: "retail" },
  { label: "Consultant", value: "consultant" },
  { label: "Sub-Contractor", value: "sub-contractor" },
  // { label: "Aluminum & Glass Customers", value: "aluminum-glass-customers" },
];
export const segmentOptions = [
  { value: "k5-block", label: "K5 Block Reinforcement Accessories" },
  { value: "k5-expamet", label: "K5 & EXPAMET (UK) Plaster Accessories" },
  { value: "k5-stone", label: "K5 Stone Cladding System" },
  { value: "k5-c-channel", label: "K5 C-Channel" },
  { value: "sealants", label: "Sealants" },
  { value: "grouts", label: "Grouts" },
]
export const contractorOptions = [
    { value: "contractor_1", label: "ABC Constructions" },
    { value: "contractor_2", label: "XYZ Builders" },
    { value: "contractor_3", label: "PQR Developers" },
    { value: "contractor_4", label: "LMN Contractors" },
    { value: "others", label: "Others" },
  ];
export const paymentTerms = [
  { value: "NET15", label: "Net 15" },
  { value: "NET30", label: "Net 30" },
  { value: "NET45", label: "Net 45" },
  { value: "NET60", label: "Net 60" },
  { value: "DUE_ON_RECEIPT", label: "Due on Receipt" },
  { value: "DUE_END_MONTH", label: "Due end of the month" },
  { value: "DUE_END_NEXT_MONTH", label: "Due end of next month" },
];

export const accountReceivable = [
  { value: "Accounts Receivable", label: "Accounts Receivable" },
];

export const requisitions = [
  { 
    id: "001", 
    label: "Requisition 1", 
    itemName: "Laptop - Dell Inspiron 15", 
    vendor: "TechWorld Pvt Ltd", 
    unit: "pcs", 
    quantity: 5, 
    rate: 45000, 
    deliverydays: 7 
  },
  { 
    id: "002", 
    label: "Requisition 2", 
    itemName: "Office Chair - Ergonomic Mesh", 
    vendor: "FurniCo Supplies", 
    unit: "pcs", 
    quantity: 10, 
    rate: 3200, 
    deliverydays: 5 
  },
  { 
    id: "003", 
    label: "Requisition 3", 
    itemName: "Printer - HP LaserJet Pro M404dn", 
    vendor: "PrintTech Solutions", 
    unit: "pcs", 
    quantity: 2, 
    rate: 18500, 
    deliverydays: 12 
  },
  { 
    id: "004", 
    label: "Requisition 4", 
    itemName: "Stationery Bundle - A4 Paper, Pens, Files", 
    vendor: "OfficeMart Traders", 
    unit: "box", 
    quantity: 20, 
    rate: 850, 
    deliverydays: 3 
  },
  { 
    id: "005", 
    label: "Requisition 5", 
    itemName: "Air Conditioner - LG 1.5 Ton Split AC", 
    vendor: "CoolBreeze Appliances", 
    unit: "pcs", 
    quantity: 3, 
    rate: 38000, 
    deliverydays: 14 
  },
];
export const vendors = [
  { id: "amitSharma", label: "Amit Sharma", value: "amit-sharma" ,country:"India",currency:"INR" ,po:" 08F-1001 " },
  { id: "priyaMehta", label: "Priya Mehta", value: "priya-mehta" ,country:"Kwait",currency:"KD" ,po:"08L-1001" },
  { id: "rahulVerma", label: "Rahul Verma", value: "rahul-verma" ,country:"Kwait" ,currency:"KD" ,po:"08L-1002" },   
  { id: "snehaKapoor", label: "Sneha Kapoor", value: "sneha-kapoor"   ,country:"United State" ,currency:"USD" ,po:"08F-1002" },
];
export const insVendors = [
  { id: "amitSharma", label: "Amit Sharma", value: "amit-sharma" ,country:"Kuwait",currency:"KD" ,po:" 08L-1001 " },
  { id: "priyaMehta", label: "Priya Mehta", value: "priya-mehta" ,country:"Kuwait",currency:"KD" ,po:"08L-1002" },
  { id: "rahulVerma", label: "Rahul Verma", value: "rahul-verma" ,country:"Kuwait" ,currency:"KD" ,po:"08L-1003" },   
  { id: "snehaKapoor", label: "Sneha Kapoor", value: "sneha-kapoor"   ,country:"Kuwait" ,currency:"KD" ,po:"08L-1004" },
];
export const insItemList = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dgmuyy9s6/image/upload/v1751693389/199db57cb1094f079c53ad3c0168e0fc_1_yuyhiv.jpg",
    name: "#300 ROMEX CABLE STRAP",
    sku: "ARL300",
    description: "",
    rate:"50",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dgmuyy9s6/image/upload/v1751693696/Screenshot_2024-07-01_112237_gya3xj.png",
    name: "PVC CONDUIT PIPE",
    sku: "PVC123",
    description: "",
    rate:"20",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dgmuyy9s6/image/upload/v1751693731/Screenshot_2024-10-07_152818_cizr27.png",
    name: "COPPER WIRE",
    sku: "CW789",
    description: "",
    rate:"35",
  },
];
export const itemList = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dgmuyy9s6/image/upload/v1751693389/199db57cb1094f079c53ad3c0168e0fc_1_yuyhiv.jpg",
    name: "#300 ROMEX CABLE STRAP",
    sku: "ARL300",
    description: "",
    rate:"300",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dgmuyy9s6/image/upload/v1751693696/Screenshot_2024-07-01_112237_gya3xj.png",
    name: "PVC CONDUIT PIPE",
    sku: "PVC123",
    description: "",
    rate:"200",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dgmuyy9s6/image/upload/v1751693731/Screenshot_2024-10-07_152818_cizr27.png",
    name: "COPPER WIRE",
    sku: "CW789",
    description: "",
    rate:"600",
  },
];

export const Customers = [
  {
    id: "1",
    label: "Ravi Sharma",
    email: "ravi@example.com",
    billingAddress: "123 Street, New Delhi",
    shippingAddress: "89 Express Road, Gurgaon",
  },
  {
    id: "2",
    label: "Anjali Verma",
    email: "anjali@example.com",
    billingAddress: "456 Avenue, Mumbai",
    shippingAddress: "789 Market Lane, Pune",
  },
];
export const salesOrderItems = [
  {
    id: "1",
    name: "Customer A",
    billingAddress: "123 New Street, Delhi",
    cost: 1000,
    shipDate: "2025-07-02",
    fixtureType: "Wall Mount",
    freightCarrier: "FedEx",
    quantity: 2,
    rate: 500,
    tax: "5",
  },
  {
    id: "2",
    name: "Customer B",
    billingAddress: "89 Express Lane, Mumbai",
    cost: 1500,
    shipDate: "2025-07-04",
    fixtureType: "Ceiling",
    freightCarrier: "Blue Dart",
    quantity: 3,
    rate: 600,
    tax: "12",
  },
];
export const categories = [
  { label: "SITE LIGHTING", value: "site-lighting" },
  { label: "SCONCE", value: "sconce" },
  { label: "PENDANT", value: "pendant" },
  { label: "EGRESS", value: "egress" },
  { label: "POLE", value: "pole" },
  { label: "FAN", value: "fan" },
  { label: "LINEAR", value: "linear" },
  { label: "LANDSCAPE", value: "landscape" },
  { label: "VANITY", value: "vanity" },
  { label: "FLOOD LIGHT", value: "flood-light" },
  { label: "TAPE LIGHT", value: "tape-light" },
  { label: "RELAY", value: "relay" },
  { label: "LIGHTING CONTROL", value: "lighting-control" },
  { label: "LAMP", value: "lamp" },
  { label: "HIGH BAY", value: "high-bay" },
  { label: "TRACK LIGHTING", value: "track-lighting" },
  { label: "DRIVER", value: "driver" },
  { label: "WALL PACK", value: "wall-pack" },
  { label: "BOLLARD", value: "bollard" },
  { label: "SERVICE", value: "service" },
  { label: "PVC CONDUIT", value: "pvc-conduit" },
  { label: "EMT CONDUIT", value: "emt-conduit" },
  { label: "ROMEX WIRE", value: "romex-wire" },
  { label: "THN WIRE", value: "thn-wire" },
  { label: "CHANDELIERS", value: "chandeliers" },
  { label: "STRING LIGHTS", value: "string-lights" },
  { label: "POST TOP", value: "post-top" },
  { label: "TOOLS", value: "tools" },
  { label: "INVERTER", value: "inverter" },
  { label: "GROUND WIRE", value: "ground-wire" },
  { label: "TRANSFORMER", value: "transformer" },
];
export const lightingVendors = [
  { label: "HUDSON VALLEY", value: "hudson_valley" },
  { label: "QUORUM INTERNATIONAL", value: "quorum_international" },
  { label: "MODERN FORMS", value: "modern_forms" },
  { label: "KICHLER", value: "kichler" },
  { label: "ROYAL PACIFIC", value: "royal_pacific" },
  { label: "AMAZON", value: "amazon" },
  { label: "OKT Lighting USA", value: "okt_lighting_usa" },
  { label: "ALL STAR LIGHTING", value: "all_star_lighting" },
  { label: "SONNEMAN", value: "sonneman" },
  { label: "Luxrite", value: "luxrite" },
  { label: "ALW", value: "alw" },
  { label: "Schoolhouse Lighting", value: "schoolhouse_lighting" },
  { label: "VISUAL COMFORT", value: "visual_comfort" },
  { label: "KUZCO", value: "kuzco" },
  { label: "SATCO", value: "satco" },
  { label: "CRYSTORAMA", value: "crystorama" },
  { label: "RESTORATION HARDWARE", value: "restoration_hardware" },
  { label: "MAXIM", value: "maxim" },
  { label: "HINKLEY", value: "hinkley" },
  { label: "HOME DECORATORS COLELCTION", value: "home_decorators_colelction" },
  { label: "PROGRESS LIGHTING", value: "progress_lighting" },
  { label: "NORA", value: "nora" },
  { label: "HUNTER", value: "hunter" },
  { label: "VOLUME", value: "volume" },
  { label: "GM LIGHTING", value: "gm_lighting" },
  { label: "American Lighting", value: "american_lighting" },
  { label: "Yardilumination.com", value: "yardilumination_com" },
  { label: "MEINUOKE", value: "meinuoke" },
  { label: "RAB LIGHTING", value: "rab_lighting" },
  { label: "BOVER BARCELONA LIGHTS", value: "bover_barcelona_lights" },
  { label: "MESTER", value: "mester" },
  { label: "LED MY PLACE", value: "led_my_place" },
  { label: "BEGA", value: "bega" },
  { label: "Shenzhen Dimi Lighting Co.", value: "shenzhen_dimi_lighting_co" },
  { label: "CRAFTMADE", value: "craftmade" },
  { label: "ET2", value: "et2" },
  { label: "TROY", value: "troy" },
  { label: "FANIMATION", value: "fanimation" },
  { label: "HOUSE OF TROY", value: "house_of_troy" },
  { label: "ENERLITES", value: "enerlites" },
  { label: "LEVITON", value: "leviton" },
  { label: "GREENCREATIVE", value: "greencreative" },
  { label: "RP LIGHTING", value: "rp_lighting" },
  { label: "NUVO", value: "nuvo" },
  { label: "HI-LITE", value: "hi_lite" },
  { label: "LIVEX", value: "livex" },
  { label: "SUN SET LIGHTING", value: "sun_set_lighting" },
  { label: "LITETRONICS", value: "litetronics" },
  { label: "INTERMATIC", value: "intermatic" },
  { label: "Norwell Lighting", value: "norwell_lighting" },
  { label: "METALUX", value: "metalux" },
  { label: "SENSORWORX", value: "sensorworx" },
  { label: "MEAN WELL", value: "mean_well" },
  { label: "WELDEDPOWER", value: "weldedpower" },
  { label: "ES", value: "es" },
  { label: "INVENTRONICS", value: "inventronics" },
  { label: "LEGRAND", value: "legrand" },
  { label: "EVERLINE", value: "everline" },
  { label: "SUNRICHER", value: "sunricher" },
  { label: "LTECH", value: "ltech" },
  { label: "VEECO", value: "veeco" },
  { label: "Elitexcel", value: "elitexcel" },
  { label: "MAXXIMA", value: "maxxima" },
  { label: "WATTSTOPPER", value: "wattstopper" },
  { label: "ECHOFLEX", value: "echoflex" },
  { label: "ACUITYCONTROLS", value: "acuitycontrols" },
  { label: "AMBIENTECH", value: "ambientech" },
  { label: "LUMINUX", value: "luminux" },
  { label: "EASEIC", value: "easeic" },
  { label: "FULHAM", value: "fulham" },
  { label: "TRIAD", value: "triad" },
  { label: "LUTRON", value: "lutron" },
  { label: "STEINEL", value: "steinel" },
  { label: "Yii lighitng", value: "yii_lighitng" },
  { label: "GALLERY HOME LIGHITNG", value: "gallery_home_lighitng" },
  { label: "LITHONIA LIGHTING", value: "lithonia_lighting" },
  { label: "GREENHECK", value: "greenheck" },
  { label: "MiniLink", value: "minilink" },
  { label: "AirLine2", value: "airline2" },
  { label: "EGLO", value: "eglo" },
  { label: "RUGGED GRADE", value: "rugged_grade" },
  { label: "NEWHOUSE", value: "newhouse" },
  { label: "SUNLITE", value: "sunlite" },
  { label: "GENERAL LIGHTING", value: "general_lightig" },
];
export const brand = [
  { label: "Luxrite", value: "luxrite" },
  { label: "Halo", value: "halo" },
  { label: "WAC LIGHTING", value: "wac_lighting" },
  { label: "HUDSON VALLEY", value: "hudson_valley" },
  { label: "QUORUM INTERNATIONAL", value: "quorum_international" },
  { label: "MODERN FORMS", value: "modern_forms" },
  { label: "KICHLER", value: "kichler" },
  { label: "ROYAL PACIFIC", value: "royal_pacific" },
  { label: "AMAZON", value: "amazon" },
  { label: "OKT", value: "okt" },
  { label: "SONNEMAN", value: "sonneman" },
  { label: "ALW", value: "alw" },
  { label: "Schoolhouse", value: "schoolhouse" },
  { label: "VISUAL COMFORT", value: "visual_comfort" },
  { label: "ALORA", value: "alora" },
  { label: "SATCO", value: "satco" },
  { label: "CRYSTORAMA", value: "crystorama" },
  { label: "RESTORATION HARDWARE", value: "restoration_hardware" },
  { label: "MAXIM", value: "maxim" },
  { label: "HINKLEY", value: "hinkley" },
  { label: "HOME DECORATORS COLLECTION", value: "home_decorators_collection" },
  { label: "PROGRESS LIGHTING", value: "progress_lighting" },
  { label: "NORA", value: "nora" },
  { label: "HOLM LIGHTING", value: "holm_lighting" },
  { label: "VOLUME", value: "volume" },
  { label: "GM LIGHTING", value: "gm_lighting" },
  { label: "American Lighting", value: "american_lighting" },
  { label: "Sparkle magic", value: "sparkle_magic" },
  { label: "MEINUOKE", value: "meinuoke" },
  { label: "RAB LIGHTING", value: "rab_lighting" },
  { label: "COOPER", value: "cooper" },
  { label: "BOVER BARCELONA LIGHTS", value: "bover_barcelona_lights" },
  { label: "MESTER", value: "mester" },
  { label: "LED MY PLACE", value: "led_my_place" },
  { label: "BEGA", value: "bega" },
  { label: "Shenzhen Dimi Lighting Co.", value: "shenzhen_dimi_lighting_co" },
  { label: "CRAFTMADE", value: "craftmade" },
  { label: "ET2", value: "et2" },
  { label: "TROY", value: "troy" },
  { label: "FANIMATION", value: "fanimation" },
  { label: "HOUSE OF TROY", value: "house_of_troy" },
  { label: "ENERLITES", value: "enerlites" },
  { label: "LEVITON", value: "leviton" },
  { label: "GREENCREATIVE", value: "greencreative" },
  { label: "RP LIGHTING", value: "rp_lighting" },
  { label: "NUVO", value: "nuvo" },
  { label: "HI-LITE", value: "hi_lite" },
  { label: "LIVEX", value: "livex" },
  { label: "SUN SET LIGHTING", value: "sun_set_lighting" },
  { label: "LITETRONICS", value: "litetronics" },
  { label: "INTERMATIC", value: "intermatic" },
  { label: "Ilex Custom Metalcraft", value: "ilex_custom_metalcraft" },
  { label: "METALUX", value: "metalux" },
  { label: "SENSORWORX", value: "sensorworx" },
  { label: "MEAN WELL", value: "mean_well" },
  { label: "WELDEDPOWER", value: "weldedpower" },
  { label: "ES", value: "es" },
  { label: "INVENTRONICS", value: "inventronics" },
  { label: "LEGRAND", value: "legrand" },
  { label: "EVERLINE", value: "everline" },
  { label: "SUNRICHER", value: "sunricher" },
  { label: "LTECH", value: "ltech" },
  { label: "VEECO", value: "veeco" },
  { label: "Elitexcel", value: "elitexcel" },
  { label: "MAXXIMA", value: "maxxima" },
  { label: "WATTSTOPPER", value: "wattstopper" },
  { label: "ECHOFLEX", value: "echoflex" },
  { label: "ACUITYCONTROLS", value: "acuitycontrols" },
  { label: "AMBIENTECH", value: "ambientech" },
  { label: "LUMINUX", value: "luminux" },
  { label: "EASEIC", value: "easeic" },
  { label: "FULHAM", value: "fulham" },
  { label: "TRIAD", value: "triad" },
  { label: "LUTRON", value: "lutron" },
  { label: "STEINEL", value: "steinel" },
  { label: "Yii Lighting", value: "yii_lighting" },
  { label: "YARD ILLUMINATION", value: "yard_illumination" },
  { label: "GALLERY HOME LIGHTING", value: "gallery_home_lighting" },
  { label: "LITHONIA LIGHTING", value: "lithonia_lighting" },
  { label: "GREENHECK", value: "greenheck" },
  { label: "MiniLink", value: "minilink" },
  { label: "AirLine2", value: "airline2" },
  { label: "KUZCO", value: "kuzco" },
  { label: "EGLO", value: "eglo" },
  { label: "RUGGED GRADE", value: "rugged_grade" },
  { label: "NEWHOUSE", value: "newhouse" },
  { label: "SUNLITE", value: "sunlite" },
  { label: "GENERAL LIGHTING", value: "general_lighting" },
  { label: "AMP", value: "amp" },
  { label: "FEIT", value: "feit" },
  { label: "SPECTRUM", value: "spectrum" },
  { label: "Newleray", value: "newleray" },
  { label: "FLEMOON", value: "flemoon" },
  { label: "Saylite", value: "saylite" },
  { label: "BEST", value: "best" },
  { label: "WSD LED INC", value: "wsd_led_inc" },
  { label: "MINKA AIR", value: "minka_air" },
  { label: "KOVACS", value: "kovacs" },
  { label: "NAFCO", value: "nafco" },
  { label: "LUMARK", value: "lumark" },
  { label: "NELSON BUBBLE LAMPS", value: "nelson_bubble_lamps" },
];
export const purchase = [
  { id: "PO-001", label: "PO-001" },
  { id: "PO-003", label: "PO-003" },
];
export const purchaseOrderDetail = [
  {
    id: 1,
    vendor: "BOYS ELECTRICAL CONTRACTORS",
    number: "PO-24-4368",
    date: "17 Apr 2024",
    status: "Confirmed",
    amount: "$54,933.96",
    reference: "M2337-146",
    orderDate: "17 Apr 2024",
    deliveryDate: "—",
    paymentTerms: "Net 30",
    received: "false",
    crmId: "123456789012345",

    deliveryAddress:
      "Ion Lighting Stock Warehouse 11483 Rocket Blvd,#2A Orlando, Florida U.S.A - 32824",
    vendorAddress:
      "253 N Vineland Ave. City of Industry, CA - 91746 626.956.4200 ",
  },
];

export const purchaseOrders = {
  "PO-001": {
    receiveNumber: "PR-22-04302",
    receiveDate: "2025-06-25",
    binLocation: "BIN-123",
    notes:
      "PLEASE EMAIL SHIPPING TRACKING NUMBER TO PK@IONLIGHTING.COM CALL PK AT 716-683-5701 WITH ANY BACKORDERS OR SHIPPING ISSUES",
  },
  "PO-003": {
    receiveNumber: "PR-22-04399",
    receiveDate: "2025-07-01",
    binLocation: "BIN-789",
    notes: "Urgent delivery needed by Friday.",
  },
};
export const Vendors = [
  {
    name: "Amit Sharma Enterprises",
    id: "ION-V-995",
  },
  {
    name: "James A. Christino",
    id: "ION-V-994",
  },
  {
    name: "Sebastian Oyegun",
    id: "ION-V-996",
  },
  {
    name: "1000BULBS.COM",
    id: "ION-V-2",
    contact: "jhale@1000bulbs.com",
  },
  {
    name: "180 VILANO GRILL",
    id: "ION-V-3",
  },
];

export const projectTemplates = [
  { value: "Project Template 1", label: "Project Template 1" },
  { value: "Project Template 2", label: "Project Template 2" },
];


export const units = [
    {value:'box', label:'box'},
    {value:'cm', label:'cm'},
    {value:'dz', label:'dz'},
    {value:'ft', label:'ft'},
    {value:'g', label:'g'},
    {value:'in', label:'in'},
    {value:'kg', label:'kg'},
    {value:'km', label:'km'},
    {value:'lb', label:'lb'},
    {value:'mg', label:'mg'},
    {value:'m', label:'m'},
    {value:'pcs', label:'pcs'},
    {value:'Box', label:'Box'},
    {value:'pc', label:'pc'},
    {value:'Service', label:'Service'},
]

export const contactNameOptions = [
  { value: "Sachin", label: "Sachin" },
  { value: "Rohit", label: "Rohit" },
  { value: "Sneha", label: "Sneha" },
  { value: "Priya", label: "Priya" },
];

export const widthUnits = [
    {value: 'kg', label: 'kg'},
    {value: 'g', label: 'g'},
    {value: 'lb', label: 'lb'},
    {value: 'oz', label: 'oz'},
]

export const productType = [
    {value:'gear', label:'Gear'},
    {value:'lighting', label:'Lighting'},
    {value:'miscellaneous', label:'Miscellaneous'},
]

export const account = [
    {value:"Sales", label:"Sales"},
    {value:"Billable Expense Income", label:"Billable Expense Income"},
    {value:"Generak Income", label:"General Income"},
]

export const carrier = [
    {value:"best-way", label:"Best Way"},
    {value:"our-truck", label:"Our Truck"},
    {value:"will-call", label:"Will Call"},
    {value:"ship-and-bill", label:"Ship And Bill"},
    {value:"drop-ship-from-texas", label:"Drop Ship From Texas"},
    {value:"ups", label:"UPS"},
    {value:"air-freight", label:"Air Freight"},
    {value:"central-transport", label:"Central Transport"},
]


export const stages = [
    {value:'qualification', label:"Qualification"},
    {value:'needAnalysis', label:"Need Analysis"},
    {value:'valueProposition', label:"Value Proposition"},
    {value:'identifyDecisionMakers', label:"Identify Decision Makers"},
    {value:'proposal', label:"Proposal"},
    {value:'negotiation', label:"Negotiation"},
    {value:'closedOne', label:"Closed One"},
    {value:'closedLost', label:"Closed Lost"},
    {value:'quoteCreate', label:"Quote Create"},
    {value:'agreement', label:"Agreement"},
    {value:'createSo', label:"Create SO"},
    {value:'paymentRecieved', label:"PaymentRecieved"},
]

export const contactRole = [
    {value:"none", label:"None"},
    {value:"developer", label:"Developer"},
    {value:"decisionMaker", label:"Decision Maker"},
    {value:"purchasing", label:"Purchasing"},
    {value:"executiveSponsor", label:"Executive Sponsor"},
    {value:"engineeringLead", label:"Engineering Lead"},
    {value:"economicDecisionMaker", label:"Economic Decision Maker"},
    {value:"productManagement", label:"Product Management"},
];
// Departments array with key:value pairs
export const departments = [
  { value: "management", label: "Management" },
  { value: "procurement", label: "Procurement" },
  { value: "site", label: "Site" },

];
export const countries = [
  { label: "Afghanistan", value: "afghanistan" },
  { label: "Albania", value: "albania" },
  { label: "Algeria", value: "algeria" },
  { label: "Andorra", value: "andorra" },
  { label: "Angola", value: "angola" },
  { label: "Antigua and Barbuda", value: "antigua-and-barbuda" },
  { label: "Argentina", value: "argentina" },
  { label: "Armenia", value: "armenia" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Azerbaijan", value: "azerbaijan" },
  { label: "Bahamas", value: "bahamas" },
  { label: "Bahrain", value: "bahrain" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Barbados", value: "barbados" },
  { label: "Belarus", value: "belarus" },
  { label: "Belgium", value: "belgium" },
  { label: "Belize", value: "belize" },
  { label: "Benin", value: "benin" },
  { label: "Bhutan", value: "bhutan" },
  { label: "Bolivia", value: "bolivia" },
  { label: "Bosnia and Herzegovina", value: "bosnia-and-herzegovina" },
  { label: "Botswana", value: "botswana" },
  { label: "Brazil", value: "brazil" },
  { label: "Brunei Darussalam", value: "brunei-darussalam" },
  { label: "Bulgaria", value: "bulgaria" },
  { label: "Burkina Faso", value: "burkina-faso" },
  { label: "Burundi", value: "burundi" },
  { label: "Cabo Verde", value: "cabo-verde" },
  { label: "Cambodia", value: "cambodia" },
  { label: "Cameroon", value: "cameroon" },
  { label: "Canada", value: "canada" },
  { label: "Central African Republic", value: "central-african-republic" },
  { label: "Chad", value: "chad" },
  { label: "Chile", value: "chile" },
  { label: "China", value: "china" },
  { label: "Colombia", value: "colombia" },
  { label: "Comoros", value: "comoros" },
  { label: "Congo (Republic of the)", value: "congo-republic" },
  { label: "Congo (Democratic Republic of the)", value: "congo-democratic-republic" },
  { label: "Costa Rica", value: "costa-rica" },
  { label: "Croatia", value: "croatia" },
  { label: "Cuba", value: "cuba" },
  { label: "Cyprus", value: "cyprus" },
  { label: "Czech Republic", value: "czech-republic" },
  { label: "Denmark", value: "denmark" },
  { label: "Djibouti", value: "djibouti" },
  { label: "Dominica", value: "dominica" },
  { label: "Dominican Republic", value: "dominican-republic" },
  { label: "Ecuador", value: "ecuador" },
  { label: "Egypt", value: "egypt" },
  { label: "El Salvador", value: "el-salvador" },
  { label: "Equatorial Guinea", value: "equatorial-guinea" },
  { label: "Eritrea", value: "eritrea" },
  { label: "Estonia", value: "estonia" },
  { label: "Eswatini", value: "eswatini" },
  { label: "Ethiopia", value: "ethiopia" },
  { label: "Fiji", value: "fiji" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "Gabon", value: "gabon" },
  { label: "Gambia", value: "gambia" },
  { label: "Georgia", value: "georgia" },
  { label: "Germany", value: "germany" },
  { label: "Ghana", value: "ghana" },
  { label: "Greece", value: "greece" },
  { label: "Grenada", value: "grenada" },
  { label: "Guatemala", value: "guatemala" },
  { label: "Guinea", value: "guinea" },
  { label: "Guinea-Bissau", value: "guinea-bissau" },
  { label: "Guyana", value: "guyana" },
  { label: "Haiti", value: "haiti" },
  { label: "Honduras", value: "honduras" },
  { label: "Hungary", value: "hungary" },
  { label: "Iceland", value: "iceland" },
  { label: "India", value: "india" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Iran", value: "iran" },
  { label: "Iraq", value: "iraq" },
  { label: "Ireland", value: "ireland" },
  { label: "Israel", value: "israel" },
  { label: "Italy", value: "italy" },
  { label: "Jamaica", value: "jamaica" },
  { label: "Japan", value: "japan" },
  { label: "Jordan", value: "jordan" },
  { label: "Kazakhstan", value: "kazakhstan" },
  { label: "Kenya", value: "kenya" },
  { label: "Kiribati", value: "kiribati" },
  { label: "Korea (North)", value: "north-korea" },
  { label: "Korea (South)", value: "south-korea" },
  { label: "Kuwait", value: "kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan" },
  { label: "Laos", value: "laos" },
  { label: "Latvia", value: "latvia" },
  { label: "Lebanon", value: "lebanon" },
  { label: "Lesotho", value: "lesotho" },
  { label: "Liberia", value: "liberia" },
  { label: "Libya", value: "libya" },
  { label: "Liechtenstein", value: "liechtenstein" },
  { label: "Lithuania", value: "lithuania" },
  { label: "Luxembourg", value: "luxembourg" },
  { label: "Madagascar", value: "madagascar" },
  { label: "Malawi", value: "malawi" },
  { label: "Malaysia", value: "malaysia" },
  { label: "Maldives", value: "maldives" },
  { label: "Mali", value: "mali" },
  { label: "Malta", value: "malta" },
  { label: "Marshall Islands", value: "marshall-islands" },
  { label: "Mauritania", value: "mauritania" },
  { label: "Mauritius", value: "mauritius" },
  { label: "Mexico", value: "mexico" },
  { label: "Micronesia", value: "micronesia" },
  { label: "Moldova", value: "moldova" },
  { label: "Monaco", value: "monaco" },
  { label: "Mongolia", value: "mongolia" },
  { label: "Montenegro", value: "montenegro" },
  { label: "Morocco", value: "morocco" },
  { label: "Mozambique", value: "mozambique" },
  { label: "Myanmar", value: "myanmar" },
  { label: "Namibia", value: "namibia" },
  { label: "Nauru", value: "nauru" },
  { label: "Nepal", value: "nepal" },
  { label: "Netherlands", value: "netherlands" },
  { label: "New Zealand", value: "new-zealand" },
  { label: "Nicaragua", value: "nicaragua" },
  { label: "Niger", value: "niger" },
  { label: "Nigeria", value: "nigeria" },
  { label: "North Macedonia", value: "north-macedonia" },
  { label: "Norway", value: "norway" },
  { label: "Oman", value: "oman" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Palau", value: "palau" },
  { label: "Palestine", value: "palestine" },
  { label: "Panama", value: "panama" },
  { label: "Papua New Guinea", value: "papua-new-guinea" },
  { label: "Paraguay", value: "paraguay" },
  { label: "Peru", value: "peru" },
  { label: "Philippines", value: "philippines" },
  { label: "Poland", value: "poland" },
  { label: "Portugal", value: "portugal" },
  { label: "Qatar", value: "qatar" },
  { label: "Romania", value: "romania" },
  { label: "Russia", value: "russia" },
  { label: "Rwanda", value: "rwanda" },
  { label: "Saint Kitts and Nevis", value: "saint-kitts-and-nevis" },
  { label: "Saint Lucia", value: "saint-lucia" },
  { label: "Saint Vincent and the Grenadines", value: "saint-vincent-and-the-grenadines" },
  { label: "Samoa", value: "samoa" },
  { label: "San Marino", value: "san-marino" },
  { label: "Sao Tome and Principe", value: "sao-tome-and-principe" },
  { label: "Saudi Arabia", value: "saudi-arabia" },
  { label: "Senegal", value: "senegal" },
  { label: "Serbia", value: "serbia" },
  { label: "Seychelles", value: "seychelles" },
  { label: "Sierra Leone", value: "sierra-leone" },
  { label: "Singapore", value: "singapore" },
  { label: "Slovakia", value: "slovakia" },
  { label: "Slovenia", value: "slovenia" },
  { label: "Solomon Islands", value: "solomon-islands" },
  { label: "Somalia", value: "somalia" },
  { label: "South Africa", value: "south-africa" },
  { label: "South Sudan", value: "south-sudan" },
  { label: "Spain", value: "spain" },
  { label: "Sri Lanka", value: "sri-lanka" },
  { label: "Sudan", value: "sudan" },
  { label: "Suriname", value: "suriname" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Syria", value: "syria" },
  { label: "Taiwan", value: "taiwan" },
  { label: "Tajikistan", value: "tajikistan" },
  { label: "Tanzania", value: "tanzania" },
  { label: "Thailand", value: "thailand" },
  { label: "Timor-Leste", value: "timor-leste" },
  { label: "Togo", value: "togo" },
  { label: "Tonga", value: "tonga" },
  { label: "Trinidad and Tobago", value: "trinidad-and-tobago" },
  { label: "Tunisia", value: "tunisia" },
  { label: "Turkey", value: "turkey" },
  { label: "Turkmenistan", value: "turkmenistan" },
  { label: "Tuvalu", value: "tuvalu" },
  { label: "Uganda", value: "uganda" },
  { label: "Ukraine", value: "ukraine" },
  { label: "United Arab Emirates", value: "united-arab-emirates" },
  { label: "United Kingdom", value: "united-kingdom" },
  { label: "United States", value: "united-states" },
  { label: "Uruguay", value: "uruguay" },
  { label: "Uzbekistan", value: "uzbekistan" },
  { label: "Vanuatu", value: "vanuatu" },
  { label: "Vatican City", value: "vatican-city" },
  { label: "Venezuela", value: "venezuela" },
  { label: "Vietnam", value: "vietnam" },
  { label: "Yemen", value: "yemen" },
  { label: "Zambia", value: "zambia" },
  { label: "Zimbabwe", value: "zimbabwe" },
];

