// Location Information Data Set
module.exports = [{
  locationOwner: "David Smith",
  locationName: "Main Office - Downtown",
  phone: "+1-555-123-4567",
  currency: "USD",
  fax: "+1-555-765-4321",
  rating: "4.5",
  parentLocation: "Regional Office",
  website: "https://mainoffice.com",
  discountFactor: "10%",
  employees: "35",
  exchangeRate: "1.3",
  phoneBurnerFollowUpDate: "2024-09-01",
  phoneBurnerLastCallOutcome: "Interested - Follow Up Needed",
  phoneBurnerLastCallTime: "2024-08-20T09:00:00Z",
  description: "Main office located in the downtown area, serving as the headquarters.",
  rolling12MonthYield: "12,500 CA$",
  averageMonthlyRevenue: "15,000 CA$",
  advisorAnnualRevenueYield: "180,000 CA$",
  clientAverageAnnualYield: "120,000 CA$",
  totalRollingRevenue: "500,000 CA$",
  clientAverageMonthlyYield: "10,000 CA$",
  advisorAverageMonthlyYield: "15,000 CA$",
  street: "456 Elm Street",
  city: "San Francisco",
  state: "California",
  postalCode: "94107",
  country: "USA",
  shipmentStreet: "789 Maple Avenue",
  shipmentCity: "Los Angeles",
  shipmentState: "California",
  shipmentPostalCode: "90001",
  shipmentCountry: "USA"
}];
