module.exports = {
  insuranceLead: [
    "None",
    "Advertisement",
    "Cold Call",
    "Employee Referral",
    "External Referral",
    "Online Store",
    "Partner",
    "Public Relations",
    "Sales Email Alias",
    "Seminar Partner",
    "Internal Seminar",
    "Trade Show",
    "Web Download",
    "chat",
  ],
  dealOwnerOptions: ["None", "Existing Business", "New Business"],
  stage: [
    "Qualification",
    "Needs Analysis",
    "Value Proposition",
    "Identify Decision Makers",
    "Presentation",
    "Application",
    "Signature",
    "Underwriting",
    "Medical",
    "APS/ MIB",
    "Decision ( Approved/Denial/ PostPone/Rated)",
    "Accepted / Re-Apply/ Change Premium",
    "Delivery",
    "Convert Life",
  ],
  forecastCategory: ["Pipeline", "Best Case", "Committed"],
}
