// models/leadsModel.js
const contacts = {
    "Contact ID": "contactID",
    "First Name": "firstName",
    "Last Name": "lastName",
    "Email": "email",
    "Contact Owner":"contactOwner",
    "Deal Stage Tracking":"dealStageTracking",
    "Status":"status",
    "Insurance Leads Source":"insuranceLeadsSource",
    "Old Database Lead":"oldDatabaseLead",
    "Mobile":"mobile",
    "Advisor Module Name":"advisorModuleName",
    "Client Address":"clientAddress",
    "Parent Client":"parentClient",
    "Clients 1st Policy Issued On":"clients1stPolicyIssuedOn",
    "Email Opt Out":"emailOptOut",
    "On Boarded Anniversary 6th":"onBoardedAnniversary6th",
    "Preferred Contact Method":"preferredContactMethod",
    "Gender":"gender",
    "Lead Created On":"leadCreatedOn",
    "Preferred Contact Time":"preferredContactTime",
    "Lead Converted On":"leadConvertedOn",
    "Do You Have A Corporation":"doYouHaveACorporation",
    "Lead Status On Conversion":"leadStatusOnConversion",
    "Does Your Corporation Have A Group Policy":"doesYourCorporationHaveAGroupPolicy",
    "On Boarded Anniversary 3rd":"onBoardedAnniversary3rd",
    "Layout":"layout",
    "On Boarded Anniversary 9th":"onBoardedAnniversary9th",
    "Currency":"currency",
    "Social Media Information":"socialMediaInformation",
    "Exchange Rate":"exchangeRate",
    "Understanding Of Insurance":"understandingOfInsurance",
    "Round Robin Processed":"roundRobinProcessed",
    "Net Worth":"netWorth",
    "Leads Score":"leadsScore",
    "Clv Corporate Commission":"clvCorporateCommission",
    "Re Run Round Robin":"reRunRoundRobin",
    "Last Clv Corporate":"lastClvCorporate",
    "Eligible Round Robin Owner Found":"eligibleRoundRobinOwnerFound",
    "Email Is Valid":"emailIsValid",
    "Clv Advisor Commission":"clvAdvisorCommission",
    "Rc SMS Opt Out":"rcSMSOptOut",
    "Last Clv Advisor":"lastClvAdvisor",
    "Email Round Robin Owner":"emailRoundRobinOwner",
    "Round Robin Assignment Date":"roundRobinAssignmentDate",
    "Re Round Robin Processed":"reRoundRobinProcessed",
    "Contact Attachments":"contactAttachments",
    "Lead Id":"leadId",
    "Insurence Partner Id":"insurencePartnerId",
    "Source":"source",
    "Source Id":"sourceId",
    "Layout Name":"layoutName",
    "WhatsApp":"whatsApp",
    "Client Policy Issue On":"clientPolicyIssueOn",
    "Date Of Birth":"dateOfBirth",
    "Round Robin Assignment Time":"roundRobinAssignmentTime",
    "Lead Created Time":"leadCreatedTime",
    "Clv Corporate Commision":"clvCorporateCommision",
    "Clv Advisor Commision":"clvAdvisorCommision",
    "Number of Products Remaining":"numberofProductsRemaining",
    "Remove From Campaign":"removeFromCampaign",
    "Email Round Robin Owner2":"emailRoundRobinOwner2",
    "Assigned Advisor":"assignedAdvisor",
    "Insurance Lead Source":"insuranceLeadSource",
    "Location":"location",
    "Auto Insurance":"autoInsurance",
    "Do You Have Corporations":"doYouHaveCorporations",
    "Immigration Services":"immigrationServices",
    "Description":"description",
    "Eligible Round Robin Owner Found1":"eligibleRoundRobinOwnerFound1",
    "Additional Contact Information":"additionalContactInformation",
    "Phone Burner Follow Up Date":"phoneBurnerFollowUpDate",
    "Phone Burner Last Call Time":"phoneBurnerLastCallTime",
    "Referral Lead Id":"referralLeadId"
};

const contactSubDetails = {
    "Life Insurance": "lifeInsurance",
    "Life Benefits": "lifeBenefits",
    "Contact ID": "contactId",
    "Service Availed Options":"serviceAvailedOptions",
    "Service Availed Loan Protection":"serviceAvailedLoanProtection",
    "Service Availed Travel Insurance":"serviceAvailedTravelInsurance",
    "Investment":"investment",
    "Group Insurance":"groupInsurance",
    "Service Availed Health And Dental Insurance":"serviceAvailedhealthAndDentalInsurance",
    "Combination Or Hybrid Insurance":"combinationOrHybridInsurance",
    "Services Availed Updated":"servicesAvailedUpdated",
    "New Service Requested":"newServiceRequested",
    "Process Stage":"processStage",
    "Other Service Requested":"otherServiceRequested",
    "Potential Business Travel Insurance":"potentialBusinessTravelInsurance",
    "Resp":"resp",
    "Rrsp Tfsa":"rrspTfsa",
    "Potential Business Health And Dental Insurance":"potentialBusinessHealthAndDentalInsurance",
    "Other Investments":"otherInvestments",
    "Potential Business Loan Protection":"potentialBusinessLoanProtection",
    "Other Living Benefits":"otherLivingBenefits",
    "Potential Business Critical Illness":"potentialBusinessCriticalIllness",
    "Potential Business Life Insurance":"potentialBusinessLifeInsurance",
    "Potential Dependent":"potentialDependent",
    "Max Number Of Potential Product":"maxNumberOfPotentialProduct",
    "Max Number Of Potential Product Applicable":"maxNumberOfPotentialProductApplicable",
    "Client Rating":"clientRating",
    "Potential Business Policy Values":"potentialBusinessPolicyValues",
    "Number Of Product Remaining":"numberOfProductRemaining",
    "Potential Dependent Completed":"potentialDependentCompleted",
    "Pending Potential Business Life Insurance":"pendingPotentialBusinesslifeInsurance",
    "Dependent Life Ins":"dependentLifeIns",
    "Pending Potential Business Critical Illness":"pendingPotentialBusinessCriticalIllness",
    "Pending Potential Business Health And Dental Insurances":"pendingPotentialBusinessHealthAndDentalInsurances",
    "Pending Potential Business Travel Insurance":"pendingPotentialBusinessTravelInsurance",
    "Pending Potential Business Resp":"pendingPotentialBusinessResp",
    "Rrsp Tfsa Mutual Funds Seg Funds":"rrspTfsaMutualFundsSegFunds",
    "Ppb Other Investments":"ppbOtherInvestments",
    "Ppb Loan Protection":"ppbLoanProtection",
    "Ppb Other Living Benefits":"ppbOtherLivingBenefits",
    "Service Offering":"serviceOffering",
    "Religion":"religion",
    "Celebrated Festivals":"celebratedFestivals",
    "Mailing Street":"mailingStreet",
    "Mailing City":"mailingCity",
    "Mailing State":"mailingState",
    "Mailing Zip":"mailingZip",
    "Mailing Country":"mailingCountry",
    "Other Street":"otherStreet",
    "Other City":"otherCity",
    "Other State":"otherState",
    "Other Country":"otherCountry",
    "Next Follow Up Date Time":"nextFollowUpDateTime",
    "Date New Service Requested":"dateNewServiceRequested",
    "Next Follow Up Date And Time":"nextFollowUpDateAndTime",
    "Service Availed Updated":"serviceAvailedUpdated",
    "Number Of Product Remaining Individuals":"numberOfProductRemainingIndividuals",
    "Dependent Critical Ins":"dependentCriticalIns",
    "Total Interaction Time":"totalInteractionTime",
    "Mailing Postal Code":"mailingpostalCode"
};

const contactEmergencyDetails = {
    "Emergency Contact Name": "emergencyContactName",
    "Emergency Contact Phone": "emergencyContactPhone",
    "Contact ID": "contactId",
    "Emergency Contact Relationship":"emergencyContactRelationship",
    "Emergency Contact Email":"emergencyContactEmail",
    "Lead Id":"leadId",
    "Deal Id":"dealId",
    "Contact Attempt":"contactAttempt",
    "Advisor Id":"advisorId"
};

const contactsSiblings = {
    "Name": "name",
    "Relationship": "relationship",
    "Contact ID": "contactId",
    "Email":"email",
    "Phone":"phone",
    "Date of Birth":"dob",
    "Lead Id":"leadId",
    "Deal Id":"dealId",
    "Age":"age",
    "Advisor Id":"advisorId"
};

const contactConversionHistory = {
    "Referral Payout till Date Health Dental": "referralPayouttillDateHealthDental",
    "Referral Payout till Date Life Travel": "referralPayouttillDateLifeTravel",
    "Contact ID": "contactId",
    "Referral Payout till Date Life":"referralPayouttillDateLife",
    "Referral Payout till Date Living Benefits":"referralPayouttillDateLivingBenefits",
    "Referral still Date Health Dental":"referralstillDateHealthDental",
    "Referral still Date Travel":"referralstillDateTravel",
    "Referral still Date Living Benefits":"referralstillDateLivingBenefits",
    "Referral till Date Life":"referraltilldateLife",
    "Referral Level":"referralLevel"
};

const partnerContact = {
    "Email": "email",
    "Address":"address",
    "Contact ID": "contactId",
    "Partner Contact":"partnerContact",
    "Parent Partner":"parentPartner"
};

module.exports = {
    contacts,
    contactSubDetails,
    contactEmergencyDetails,
    contactsSiblings,
    contactConversionHistory,
    partnerContact
};