// models/usersModel.js
const advisors = {
    "Advisor Id":"appAdvisorId",
    "First Name": "firstName",
    "Last Name": "lastName",
    "Email": "email",
    "Phone": "phone",
    "Mobile": "mobile",
    "State": "state",
    "Country": "country",
    "Status":"status",
    "Advisor Owner":"advisorOwner",
    "Currency":"currency",
    "Lead Source":"leadSource",
    "Date Of Hire":"dateOfHire",
    "Advisor Mudule Name":"advisorMuduleName",
    "Cessation Date":"cessationDate",
    "Date Of Birth":"dateOfBirth",
    "Advisors Licence Number":"advisorsLicenceNumber",
    "Additional Contact Info":"additionalContactInfo",
    "Eo Policy Number":"eoPolicyNumber",
    "Social Media":"socialMedia",
    "Course Registration Date":"courseRegistrationDate",
    "Licence Expiry Date":"licenceExpiryDate",
    "Cipr Number":"ciprNumber",
    "Eo Policy Expiry Date":"eoPolicyExpiryDate",
    "App ID":"appID",
    "Assigned Advisor":"assignedAdvisor",
    "Inactive Advisor":"inactiveAdvisor",
    "My Calendar":"myCalendar",
    "Lead Status":"leadStatus",
    "Llqp Licensed":"llqpLicensed",
    "Insurance Advisor":"insuranceAdvisor",
    "Since How Long":"sincehowLong",
    "Probem Looking To Solve":"probemLookingToSolve",
    "How Long Licensed":"howLongLicensed",
    "What Looking For":"whatLookingFor",
    "Location":"location",
    "Hire Level":"hireLevel",
    "Hire Team Name":"hireTeamName",
    "Hire Type":"hireType",
    "Hire Team Leg":"hireTeamLeg",
    "Team Generation Number":"teamGenerationNumber",
    "Landline":"landline",
    "Are You Licensed As Annsurance Advisor":"areyouLicensedAsAnnsuranceAdvisor",
    "Insurance Partner Listing":"insurancePartnerListing",
    "Exchange Rate":"exchangeRate",
    "Lead Id":"leadId",
    "Advisor Lead Source":"advisorLeadSource",
    "Description":"description",
    "Email Opt Out":"emailOptOut",
    "Remove From Campaign":"removeFromCampaign",
    "Advisors Date of Birth":"advisorsDateofBirth",
    "Vendor":"vendor",
    "Additional Contact Information":"additionalContactInformation",
    "Reviewedason":"reviewedason",
    "Whatsapp":"whatsapp",
    "Is Social":"isSocial",
    "Celebrated Festivals":"celebratedFestivals",
    "Religion":"religion",
    "Postal Code":"postalCode",
    "Catalyst Id":"catalystId",
    "Layout":"layout",
    "Supervisa Payout":"supervisaPayout",
    "Premium Percentage":"premiumPercentage",
    "Fyc Percentage":"fycPercentage",
    "Product Cataegory":"productCataegory",
    "Old Lead Database":"oldLeadDatabase",
    "Location2":"location2",
    "Living Benefits":"livingBenefits",
    "Email Is Valid":"emailIsValid",
    "Source Id":"sourceId",
    "Source":"source"
};

const advisorCredential = {
    "Advisor Id":"advisorCredentialsOwner",
    "Advisor Status":"advisorStatus",
    "Mga":"mga",
    "User Id":"userId",
    "Contracted Advisor Listing":"contractedAdvisorListing",
    "Insurance Partner Listing":"insurancePartnerListing",
    "Source Id":"sourceId",
    "Source":"source"
}

const advisorBonus = {
    "Advisor Id":"advisorId",
    "Year":"year",
    "Bonus Amount":"bonusAmount",
    "Bonus Amount 2020":"bonusAmount2020"
}

const advisorFyc = {
    "Advisor Id":"advisorId",
    "Year":"year",
    "Fyc":"fyc"
}

const advisorSubDetails = {
    "Advisor Id":"advisorId",
    "Organization Level":"organizationLevel",
    "Team Name":"teamName",
    "Employment Type":"employmentType",
    "Team Leg":"teamLeg",
    "Reviewed Date":"reviewedDate",
    "Generation Number":"generationNumber",
    "Phone":"phone",
    "Fax":"fax",
    "Secondary Email":"secondaryEmail",
    "Skype":"skype",
    "Facebook":"facebook",
    "Twitter":"twitter",
    "Linked In":"linkedIn",
    "Google Review":"googleReview",
    "Youtube Video":"youtubeVideo",
    "Street":"street",
    "Province":"province",
    "City":"city",
    "Postal Code":"postalCode",
    "Insurance Partner":"insurancePartner",
    "Bonus Level":"bonusLevel",
    "Fyc":"fyc",
    "Payout Level":"payoutLevel",
    "Premium":"premium",
    "Life Career Preferences":"lifeCareerPreferences",
    "Desired Timeline":"desiredTimeline",
    "Offering":"offering",
    "Is This a Reassignment":"isthisaReassignment",
    "Best Time To Call":"bestTimeToCall",
    "Referral Name Client":"referralNameClient",
    "If Referred by Advisor":"ifreferredbyAdvisor",
    "Existing Policy Renewal Due By":"existingPolicyRenewalDueBy",
    "Submit Page Url":"submitPageUrl",
    "Assigned Campaigns":"assignedCampaigns",
    "Potential Business":"potentialBusiness",
    "Insurance Lead Scoring Positive Score":"insuranceLeadScoringPositiveScore",
    "Insurance Leads Scoring Touch Point Score":"insuranceLeadsScoringTouchPointScore",
    "Insurance Lead Scoring Negative Score":"insuranceLeadScoringNegativeScore",
    "Insurance Lead Scoring Score":"insuranceLeadScoringScore",
    "Insurance Lead Positive Touch Scoring Score":"insuranceLeadPositiveTouchScoringScore",
    "Insurance Lead Negative Touch Scoring Score":"insuranceLeadNegativeTouchScoringScore",
    "Coverage Lokking For":"coverageLokkingFor",
    "Round Robin Assignment Time":"roundRobinAssignmentTime",
    "Gender Predication":"genderPredication",
    "Next Follow Up Date Time":"nextFollowUpDateTime",
    "Dob":"dob",
    "Lead Created On":"leadCreatedOn",
    "Combination Hybird":"combinationHybird",
    "Round Robin Processed1":"roundRobinProcessed1",
    "Email Round Robin Owner2":"emailRoundRobinOwner2",
    "Eligible Round Robin Owner Found1":"eligibleRoundRobinOwnerFound1",
    "Re Run Round Robin":"rerunroundrobin",
    "Health And Dental Insurance":"healthAndDentalInsurance",
    "rCSMS Opt Out":"rCSMSOptOut",
    "Ad Account":"adAccount",
    "Ad Account Id":"adAccountId",
    "Ad Campaign":"adCampaign",
    "Ad Campaign Id":"adCampaignId",
    "FaceBook Page":"faceBookPage",
    "FaceBook Page Id":"faceBookPageId",
    "Cost Per Lead":"costPerLead",
    "Ad Set":"adSet",
    "Ad Set Id":"adSetId",
    "Facebook Ad":"facebookAd",
    "Ad Id":"adId",
    "Lead Form":"leadForm",
    "Lead Form Id":"leadFormId",
    "Skype ID":"skypeID",
    "Instagram ID":"instagramID",
    "Linkedin1":"linkedin1",
    "Fb1":"fb1",
    "Twitter1":"twitter1",
    "Youtube Vedio":"youtubeVedio",
    "Net Worth":"netWorth",
    "Add Contact Info":"addContactInfo",
    "Gender":"gender",
    "Gender Prediction":"genderprediction",
    "Do You Have Life Insurance":"doYouHaveLifeInsurance",
    "Existing Insurance Policy":"existingInsurancePolicy",
    "Service Requested":"serviceRequested",
    "Citizenship Status":"citizenshipStatus",
    "Group Insurance":"groupInsurance",
    "Referred By":"referredBy",
    "Understanding Of Insurance":"understandingOfInsurance",
    "Do You Own Home In Canada":"doYouOwnHomeInCanada",
    "Referral Source":"referralSource",
    "Preferred Contact Time":"preferredContactTime",
    "Preferred Contact":"preferredContact",
    "Loan Protection":"loanProtection",
    "Social Media Info":"socialMediaInfo",
    "Fb Ad Info":"fbAdInfo",
    "Travel Insurance":"travelInsurance",
    "Investment":"investment",
    "Life Insurance":"lifeInsurance",
    "Mailing Street":"mailingStreet",
    "Mailing City":"mailingCity",
    "Mailing State":"mailingState",
    "Mailing Postal Code":"mailingPostalCode",
    "Mailing Country":"mailingCountry"
}

module.exports = {
    advisors,
    advisorCredential,
    advisorBonus,
    advisorFyc,
    advisorSubDetails
};