//// models/leadsModel.js
const leads = {
        "Lead ID":"leadID",
        "First Name":"firstName",
        "Last Name":"lastName",
        "Email":"email",
        "Secondary Email":"secondaryEmail",
        "Currency":"currency",	
        "Exchange Rate":"exchangeRate",
        "Email Opt Out":"emailOptOut",
        "Mobile":"mobile",
        "Lead Source":"insuranceLeadSource",
        "Lead Status":"leadStatus",
        "Postal Code":"whatIsYourPostalCode",
        "Description":"description",
        "Insurance Lead Owner":"insuranceLeadOwner",
        "Insurance Lead Status":"insuranceLeadStatus",
        "Whatsapp":"whatsapp",
        "Lead Status Stage":"leadStatusStage",
        "Assigned Advisor":"assignedAdvisor",
        "Email Is Valid":"emailIsValid",
        "Remove From Campaign":"removeFromCampaign",
        "Date Of Birth":"dateOfBirth",
        "Best Time To Call":"bestTimeToCall",
        "Gender":"gender",
        "Is This a Reassignment":"isThisaReassignment",
        "Location Name":"locationName",
        "Referred By":"referredBy",
        "Net Worth":"netWorth",
        "Preferred Contact Method":"preferredContactMethod",
        "Preferred Contact Time":"preferredContactTime",
        "Social Media Information":"socialMediaInformation",
        "Round Robin Processed":"roundRobinProcessed",
        "Citizenship Status":"citizenshipStatus",
        "Email Round Robin Owner":"emailRoundRobinOwner",
        "Understanding Of Insurance":"understandingOfInsurance",
        "Existing Insurance Policy":"existingInsurancePolicy",
        "Eligible Round Robin Owner Found":"eligibleRoundRobinOwnerFound",
        "Do You Own a Home In Canada":"doYouOwnaHomeInCanada",
        "Do You have Life Insurance":"doYouhaveLifeInsurance",
        "Old Database Lead":"oldDatabaseLead",
        "Next Follow Up Date Time":"nextFollowUpDateTime",
        "Gender Prediction Score":"genderPredictionScore",
        "Re Run Round Robin":"reRunRoundRobin",
        "Rc Sms Opt Out":"rcSmsOptOut",
        "Submit Page URL":"submitPageURL",
        "Are You Ready To Purchase This Life Insurance Poli":"areYouReadyToPurchaseThisLifeInsurancePoli",
        "Assigned Campaigns":"assignedCampaigns",
        "Are You Ready To Purchase This Life Insurance Pol":"areYouReadyToPurchaseThisLifeInsurancePol",
        "Gender Prediction":"genderPrediction",
        "Inbox URL":"inboxURL",
        "Additional Contact Information":"additionalContactInformation",
        "AreYouLLQPLicensed":"areYouLLQPLicensed",
        "Phone Burner Follow UpDate":"phoneBurnerFollowUpDate",
        "Phone Burner Last Call Outcome":"phoneBurnerLastCallOutcome",
        "Phone Burner Last Call Time":"phoneBurnerLastCallTime",
        "Driver License No":"driverLicenseNo",
        "Vehicle Year":"vehicleYear",
        "When Was Your Vehicle Made":"whenWasYourVehicleMade",
        "Phone Number":"phoneNumber",
        "Name":"name",
        "Add Email 1":"addEmail1",
        "Quote":"quote",
        "Deposit":"deposit",
        "Date Of Birth 1":"dateOfBirth1",
        "Child Age":"childAge",
        "How Much You Like To Start The Plan":"howMuchYouLikeToStartThePlan",
        "How Much Amount Want To Start With":"howMuchAmountWantToStartWith",
        "Date Of Birth Of Traveler":"dateOfBirthOfTraveler",
        "Religion":"religion",
        "Celebrated Festivals":"celebratedFestivals",
        "Round Robin Assignment Time":"roundRobinAssignmentTime",
        "Layout Name":"layoutName",
        "Source Id":"sourceId",
        "Source":"source",
        "Where Would You Be Travellingto":"whereWouldYouBeTravellingto",
        "What type of Student":"whattypeofStudent",
        "Trip Type":"tripType",
        "Start Date Of Coverage":"startDateOfCoverage",
        "If Referred By Advisor Or External Referral":"ifReferredByAdvisorOrExternalReferral",
        "Existing Policy Renewal Due By":"existingPolicyRenewalDueBy",
        "Coverage You Are Looking For":"coverageYouAreLookingFor",
        "Fax":"fax",
        "Ready For Purchase":"readyForPurchase",
        "Lead Created On":"leadCreatedOn",
        "Lead Referral Id":"leadReferralId"
    
    // "Lead ID": "leadID",
    // "First Name": "firstName",
    // "Last Name": "lastName",
    // "Email": "email",
    // "Secondary Email": "secondaryEmail",
    // "Currency": "currency",
    // "Exchange Rate": "exchangeRate",
    // "Email Opt Out": "emailOptOut",
    // "Mobile": "mobile",
    // "Lead Source": "insuranceLeadSource",
    // "Lead Status": "leadStatus",
    // "Postal Code": "whatIsYourPostalCode",
    // "Description": "description"
};

const leadInformations = {
        "Street Address":"street",
        "City":"city",
        "Lead ID":"leadId",
        "Contact":"contact",
        "Contact Id":"contactId",
        "Best Time To Call":"bestTimeToCall",
        "Date Of Birth 1":"dateOfBirth1",
        "If Referred By Advisor":"ifreferredbyAdvisor",
        "Is This A Reassignment":"isthisAReassignment",
        "Referred By":"referredBy",
        "Investments1":"investments1",
        "Preferred Contact Method2":"preferredContactMethod2",
        "Preferred Contact Time2":"preferredContactTime2",
        "Citizenship Status1":"citizenshipStatus1",
        "Understanding Of Insurance1":"understandingOfInsurance1",
        "Existing Insurance Policy2":"existingInsurancePolicy2",
        "Do You Own A Home In Canada":"doYouOwnAHomeInCanada",
        "Existing Policy Renewal Due By":"existingPolicyRenewalDueBy",
        "Do You Have Life Insurance":"doYouHavelifeInsurance",
        "Submit Page Url":"submitPageUrl",
        "Country":"country",
        "Assigned Campaigns":"assignedCampaigns",
        "State":"state",
        "Linked In1":"linkedIn1",
        "Zip Code":"zipCode",
        "Facebook Ad Information":"facebookAdInformation",
        "Twitter1":"twitter1",
        "Services Requested":"servicesRequested",
        "Skype Id":"skypeId",
        "Instagram1":"instagram1",
        "Insurence Leads Scoring Positive Touch Point Score":"insurenceLeadsScoringPositiveTouchPointScore",
        "Insurence Leads Scoring Negative Score":"insurenceLeadsScoringNegativeScore",
        "Insurance Leads Scoring Score":"insuranceLeadsScoringScore",
        "Insurence Leads Scoring Positive Score":"insurenceLeadsScoringPositiveScore",
        "Insurence Leads Scoring Negative Touch Point Score":"insurenceLeadsScoringNegativeTouchPointScore",
        "Coverage You Are Looking For":"coverageYouAreLookingFor",
        "Insurance Lead Scoring Positive Score":"insuranceLeadScoringPositiveScore",
        "Insurance Lead Scoring Negative Touch Point Score":"insuranceLeadScoringNegativeTouchPointScore",
        "Gender1":"gender1",
        "Additional Contact Information":"additionalContactInformation",
        "Networth2":"networth2",
        "Database Lead1":"databaseLead1",
        "Gender Prediction1":"genderPrediction1",
        "Exchange Rate1":"exchangeRate1",
        "Currency1":"currency1",
        "Lead Created On1":"leadCreatedOn1",
        "Linkdin1":"linkdin1",
        "FaceBook":"faceBook",
        "Insurance Lead Scoring Touch Point Score":"insuranceLeadScoringTouchPointScore",
        "Insurance Lead Scoring Positive Touch Point Score":"insuranceLeadScoringPositiveTouchPointScore",
        "Insurance Lead Scoring Negative Score":"insuranceLeadScoringNegativeScore",
        "Old Database Lead1":"oldDatabaseLead1",
        "Ad Account":"adAccount",
        "Ad Set":"adSet",
        "Ad Campaign":"adCampaign",
        "Facebook Ad":"facebookAd",
        "Ad Id":"adId",
        "Facebook Page":"facebookPage",
        "Lead Form":"leadForm",
        "Ad Account Id":"adAccountId",
        "Ad Set Id":"adSetId",
        "Ad Campaign Id":"adCampaignId",
        "Facebook Page Id":"facebookPageId",
        "Lead Form Id":"leadFormId",
        "Cost Per Lead":"costPerLead",
        "Instagram Id":"instagramId",
        "Year":"year",
        "Referral Client":"referralClient",
        "Referral Source":"referralSource",
        "Referral Other Than Client":"referralOtherThanClient",
        "Product Category Referred":"productCategoryReferred",
        "If Referred By Advisor Or External":"ifReferredByAdvisorOrExternal",
        "Existing Renewal Policy Due By":"existingRenewalPolicyDueBy",
        "Skype Id1":"skypeId1",
        "Round Robin Assignment Time1":"roundRobinAssignmentTime1",
        "Lead Potential Business Policy Values":"leadPotentialBusinessPolicyValues",
        "Insurance Lead Score":"insuranceLeadScore",
        "Facebook1":"facebook1",
        "Insurance Leads Scoring Positive Touch Point Score":"insuranceLeadsScoringPositiveTouchPointScore",
        "Insurance Leads Scoring Negative Score":"insuranceLeadsScoringNegativeScore",
        "Whatsapp":"whatsapp",
        "Phone Burner Last Outcome":"phoneBurnerLastOutcome",
        "Catalyst Id":"catalystId",
        "Is This Reassignment":"isThisReassignment",
        "Do You Own Home In Cananda":"doYouOwnHomeInCananda",
        "Additional Contact Information1":"additionalContactInformation1",
        "Lead Info Additional Contact Information":"leadInfoAdditionalContactInformation",
        "Home Insurance":"homeInsurance",
        "Location Name2":"locationName2"
    
    // "Street Address": "street",
    // "City": "city",
    // "Lead ID": "leadId" 
};

const leadDescription = {
        "Looking For Advisor?":"LookingForAdvisor",
        "What time frame you like to move to be a advisor?":"whatTimeFrameYouLikeToMoveToBeaAdvisor	",
        "Lead ID":"leadId",
        "Type Of Insurance Looking":"typeOfInsuranceLooking",
        "What Policy Do You Want":"whatPolicyDoYouWant",
        "Age Of 1st Traveler":"ageOf1stTraveler",
        "Enterage Of 2nd Traveler":"enterageOf2ndTraveler",
        "Traveler Start Date":"travelerStartDate",
        "Traveler End Date":"travelerEndDate",
        "Coverage You Are Looking For":"coverageYouAreLookingFor",
        "Pre Existing Medical Conditions":"preExistingmedicaLconditions",
        "How Much Coverage Is Required":"howMuchCoverageIsRequired",
        "Can You Please Let Me Know Premium Payment Mode":"canYouPleaseLetMeKnowPremiumPaymentMode",
        "Tobacco Used":"tobaccoused",
        "What Type Of Term Plan Are You Looking For":"whatTypeOfTermPlanAreYouLookingFor",
        "Do You Want Critical Illness Insurance With Money":"doYouWantCriticalIllnessInsuranceWithMoney",
        "How Do You Consider Your Health":"howDoYouConsiderYourHealth",
        "Whats Your Profession":"whatsYourProfession",
        "How Many Critical Illness Coverage You Need":"howManyCriticalIllnessCoverageYouNeed",
        "How Much Monthly Benefit Do You Need":"howMuchMonthlyBenefitDoYouNeed",
        "Select The Duration Of The Coverage":"selectTheDurationOfTheCoverage",
        "You Are Seeking CoverageFor":"youAreSeekingCoverageFor",
        "Enter The Amount Of Mortgage Coverage Required":"enterTheAmountOfMortgageCoverageRequired",
        "Whats Your Age":"whatsYourAge",
        "Do You Have Any Medical Issue":"doYouHaveAnyMedicalIssue",
        "Resp Accounts For Your Child Childrens":"respAccountsForYourChildChildrens",
        "Secure Your Childs Future With Higher Education":"secureYourChildsFutureWithHigherEducation",
        "How Much Do You Want To Save Monthly":"howMuchDoYouWantToSaveMonthly",
        "Growth On Your Investment In Resp Account":"growthOnYourInvestmentInRespAccount",
        "Would Like To Increase Monthly Deposits":"wouldLikeToIncreaseMonthlyDeposits",
        "Qualify For 15 Bonus Of Your Resp Account":"qualifyFor15BonusOfYourRespAccount",
        "How Many Childrens Do You Have":"howManyChildrensDoYouHave",
        "Eligible To Get Extra 2000 In Government Grants":"eligibleToGetExtra2000InGovernmentGrants",
        "What Is Your Residency Status In Canada":"whatIsYourResidencyStatusInCanada",
        "Deposit Every Month Towards Your Child Education":"depositEveryMonthTowardsYourChildEducation",
        "How Long Do You Need Coverage For":"howLongDoYouNeedCoverageFor",
        "Would You Like To Know How Resp Works":"wouldYouLikeToKnowHowRespWorks",
        "Money Require To Complete Your Childs Education":"moneyRequireToCompleteYourChildsEducation",
        "Select Your Age Bracket":"selectYourAgeBracket",
        "One Million Inan Resp Account At Retirement":"oneMillionInanRespAccountAtRetirement",
        "How Much Do You Want To Save Yearly":"howMuchdoYouWantToSaveYearly",
        "Do You Wan To Deposit Monthly Or Yearly Premium":"doYouWanToDepositMonthlyOrYearlyPremium",
        "Would You Like To Know How Tfsa Works":"wouldYouLikeToKnowHowTfsaWorks",
        "What Age Do You Want To Start The Withdrawal From":"whatageDoYouWanttostartTheWithdrawalFrom",
        "What Kind Of Businesss Is It":"whatKindOfBusinesssIsIt",
        "Would You Like To Know How Rrsp Works":"wouldYouLikeToKnowHowRrspWorks",
        "One Million In An Tfsa Account At Retirement":"oneMillionInAnTfsaAccountAtRetirement",
        "Are You An Owner Or Employee Of The Business":"areYouAnOwnerOrEmployeeOfTheBusiness",
        "Gcl Id Field":"gclidField",
        "Are You Looking For Drug And Dental Or Just Drug Pla":"areYouLookingForDrugAndDentalOrJustDrugPla",
        "Are You Licensed As An Insurance Advisor":"areYouLicensedAsAnInsuranceAdvisor",
        "Would You Like To Know How Super Visa Insurance Wo":"wouldYouLikeToKnowHowSuperVisaInsuranceWo",
        "Existing Health Conditions":"existingHealthConditions",
        "Single Or Family Plan":"singleOrFamilyPlan",
        "Monthly Premium Knowledge":"monthlyPremiumKnowledge",
        "Previous Policy With Us":"previousPolicyWithUs",
        "Coverage For Drug And Dental Cost":"coverageForDrugAndDentalCost",
        "Prescription Medication Coverage":"prescriptionMedicationCoverage",
        "Super Visa Insurance":"superVisaInsurance",
        "Secure Your Child Future With Higher Education":"secureYourChildFutureWithHigherEducation",
        "Money Require To Complete Your Child Education":"moneyRequireToCompleteYourChildEducation",
        "Total Dependents":"totalDependents",
        "Dependent Age 1":"dependentAge1",
        "Dependent Age 2":"dependentAge2",
        "Dependent Age 3":"dependentAge3",
        "Dependent Age 4":"dependentAge4",
        "Dependent Age 5":"dependentAge5",
        "Dependent Age 6":"dependentAge6"
    
    // "Looking For Advisor?": "LookingForAdvisor",
    // "What time frame you like to move to be a advisor?": "whatTimeFrameYouLikeToMoveToBeaAdvisor",
    // "Lead ID": "leadId"
};

const leadService = {
        "Potential Business":"potentialBusiness",
        "Loan Protection":"loanProtection",
        "Lead ID":"leadId",
        "Services Requested":"servicesRequested",
        "Life Insurance":"lifeInsurance",
        "Investments":"investments",
        "Living Benefits":"livingBenefits",
        "Group Insurance":"groupInsurance",
        "Travel Insurance":"travelInsurance",
        "Combination Or Hybrid Insurance":"combinationOrHybridInsurance",
        "Auto Insurance":"autoInsurance",
        "Health And Dental Insurance":"healthAndDentalInsurance",
        "Home Insurance":"homeInsurance",
        "Business Liability Insurance":"businessLiabilityInsurance",
        "Immigration Services":"immigrationServices",
        "Campaign Id Data":"campaignidData",
        "Network Data":"networkData",
        "Ad Group Id Data":"adgroupidData",
        "Device Data":"deviceData",
        "Match Type Data":"matchtypeData",
        "Keyword Data":"keywordData",
        "Gcl Id Data":"gclidData",
        "Lp Url Data":"lpUrlData"
    
    // "Potential Business": "potentialBusiness",
    // "Loan Protection": "loanProtection",
    // "Lead ID": "leadId"
};

const leadConversionHistory = {
    "Date Of Interaction":"dateOfInteraction",
    "Interaction Type":"interactionType",
    "Lead ID":"leadId",
    "Contact Id":"contactId",
    "Time Of Interaction":"timeOfInteraction",
    "Time Spent":"timeSpent",
    "Comments":"comments",
    "Interaction Outcome":"interactionOutcome",
    "Probability Of Closure":"probabilityOfClosure",
    "Contact Attempt":"contactAttempt",
    "Referral Till Date Life":"referraltilldateLife"
};

module.exports = {
    leads,
    leadInformations,
    leadDescription,
    leadService,
    leadConversionHistory
};