// models/usersModel.js
const policies = {
    "Policy ID": "policyID",
    "Policy Owner":"policyOwner",
    "Layout":"layout",
    "Policy Name":"policyName",
    "Client":"client",
    "Contract Number":"contractNumber",
    "Email":"email",
    "Coverage Amount":"coverageAmount",
    "Client Mobile":"clientMobile",
    "Investment":"investment",
    "Client Address":"clientAddress",
    "Frequency":"frequency",
    "Location Discount Factor":"locationDiscountFactor",
    "Policy Advisor":"policyAdvisor",
    "Advisor Commission":"advisorCommission",
    "Status":"status",
    "Product Fyc Percent":"productFycPercent",
    "Corporate Bonus Percent":"corporateBonusPercent",
    "Offering Id":"offeringId",
    "Type":"type",
    "Pb Compliance":"pbCompliance",
    "Bonus Level":"bonusLevel",
    "First Policy":"firstPolicy",
    "Advisor Bonus Of Fyc":"advisorBonusOfFyc",
    "Note":"note",
    "Client Campaign Source":"clientCampaignSource",
    "Conduct Compliance":"conductCompliance",
    "Offering Name":"offeringName",
    "Is Client The Insured":"isClientTheInsured",
    "Are There Multiple Insured":"areThereMultipleInsured",
    "Attachment Link":"attachmentLink",
    "Are There Multiple Beneficiary":"areThereMultipleBeneficiary",
    "Number of Beneficiaries":"numberofBeneficiaries",
    "Are There Trustee For This Policy":"areThereTrusteeForThisPolicy",
    "Application On":"applicationOn",
    "Trust Dissolution Date":"trustDissolutionDate",
    "Trust Document Recieved And Uploaded":"trustDocumentRecievedAndUploaded",
    "No Trustees":"noTrustees",
    "Location":"location",
    "Deal":"deal",
    "Contract Name":"contractName",
    "Monthly Annual Contribution":"monthlyAnnualContribution",
    "Initial Deposit":"initialDeposit",
    "Initial Contribution":"initialContribution",
    "Total Contribution":"totalContribution",
    "Module":"module",
    "Advisor Bonus Level":"advisorBonusLevel",
    "Comments On Rating":"commentsOnRating",
    "Number Of Insured":"numberOfInsured",
    "Is Client A Beneficiary":"isClientABeneficiary",
    "Advisor Name":"advisorName",
    "Number Of Trustee":"numberOfTrustee",
    "Cegs":"cegs",
    "Registered":"registered",
    "Contact ID":"contactID",
    "Source":"source",
    "Source Id":"sourceId",
    "Insurance Company Account":"insuranceCompanyAccount",
    "Exchange Rate":"exchangeRate",
    "Update Offering Id":"updateOfferingId",
    "Update Policy Status":"updatePolicyStatus",
    "Trigger Supervisa":"triggerSupervisa",
    "Send To Policy Start Date Email Track":"sendToPolicyStartDateEmailTrack",
    "Send To Bot Result":"sendToBotResult",
    "Client Beneficiary":"clientBeneficiary",
    "Trustees Policy":"trusteesPolicy",
    "Currency":"currency",
    "Corporate Commission":"corporateCommission",
    "Location Commission":"locationCommission",
    "Policy Number":"policyNumber",
    "Policy Premium I":"policyPremiumI",
    "Policy Type":"policyType",
    "Policy Status":"policyStatus",
    "Premium Frequency":"premiumFrequency",
    "Advisor Commision Recieved":"advisorCommisionRecieved",
    "Advisor Probhited Behaviour Compliance":"advisorProbhitedBehaviourCompliance",
    "Client First Policy":"clientFirstPolicy",
    "Advisor Code Of Conduct Complaince":"advisorCodeOfConductComplaince",
    "Issued By":"issuedBy",
    "Whatsapp":"whatsapp",
    "Relationship To Primary Annuitment":"relationshipToPrimaryAnnuitment",
    "Phone Updated":"phoneUpdated",
    "Number of Beneficiaries upto 4":"numberofBeneficiariesupto4",
    "Relation to Primary Annuitant":"relationtoPrimaryAnnuitant",
    "Beneficiary Gender":"beneficiaryGender",
    "Are There Multiple Beneficiaries":"arethereMultipleBeneficiaries"
};

const policyCommission = {
    "Policy ID":"policyId",
    "Month Premium":"monthPremium",
    "Gc Comm":"gcComm",
    "Gl Comm":"glComm",
    "Na Coom":"naCoom",
    "Nc Comm":"ncComm",
    "Nl Comm":"nlComm"
};

const supervisaPolicySubDetails = {
    "Policy ID":"policyId",
    "Day Wise Advisor Commision":"dayWiseAdvisorCommision",
    "Day Wise Corporate Commision":"dayWiseCorporateCommision",
    "Day Wise Location Commision":"dayWiseLocationCommision",
    "Policy Month":"policyMonth",
    "Total Gross Corpoarate Com":"totalGrossCorpoarateCom",
    "Total Gross Location Commision":"totalGrossLocationCommision",
    "Total Gross Advisor Commission":"totalGrossAdvisorCommission",
    "Total Net Location Commission":"totalNetLocationCommission",
    "Total Net Corporate Commision":"totalNetCorporateCommision",
    "Location Commission":"locationCommission",
    "Advisor Commission":"advisorCommission",
    "Total Net Advisor Commission":"totalNetAdvisorCommission",
    "Total Net Corporate Com":"totalNetCorporateCom",
    "Total Gross Location Com":"totalGrossLocationCom",
    "Update Commission":"updateCommission",
    "Corporate Commission":"corporateCommission",
    "Corporate Commission Amount":"corporateCommissionAmount",
    "Total Net Advisor policy Commission":"totalNetAdvisorpolicyCommission",
    "Update Policy Commission":"updatePolicyCommission",
    "Advisor Policy Commission":"advisorPolicyCommission",
    "Location Policy Commission":"locationPolicyCommission",
    "Corporate Policy Commission":"corporatepolicyCommission",
    "Total Net Location Policy Commission":"totalNetLocationpolicyCommission"
};

const policySubDetails = {
    "Policy ID":"policiesId",
    "Application Submitted On":"applicationSubmittedOn",
    "Application Postponed To":"applicationPostponedTo",
    "Next Follow Up Date":"nextFollowUpDate",
    "Policy Decline Date":"policyDeclineDate",
    "Policy Approved Date":"policyApprovedDate",
    "Declined Reason":"declinedReason",
    "Approval Rating":"approvalRating",
    "Policy Start Date":"policyStartDate",
    "Application Medical Requirement":"applicationMedicalRequirement",
    "Policy Issued Date":"policyIssuedDate",
    "Policy Picked Up On":"policyPickedUpOn",
    "Early Return Application Cancelled":"earlyReturnApplicationCancelled",
    "Early Return Amendment Requested":"earlyReturnAmendmentRequested",
    "Premium Paid During Pick Up Period":"premiumPaidDuringPickUpPeriod",
    "Early Return Amendment Requested For":"earlyReturnAmendmentRequestedFor",
    "Early Return Amendment Completed Date":"earlyReturnAmendmentCompletedDate",
    "Policy Renewal Date":"policyRenewalDate",
    "Renewal Medical Conformation Number":"renewalMedicalConformationNumber",
    "Policy Expires On":"policyExpiresOn",
    "Any Current Claims On This Policy":"anyCurrentClaimsOnThisPolicy",
    "Claim Amount":"claimAmount",
    "Any Past Claims On The Policy":"anyPastClaimsOnThePolicy",
    "Date Of Claim":"dateOfClaim",
    "Claim Closed":"claimClosed",
    "Reason Of Claim":"reasonOfClaim",
    "Claim Submitted":"claimSubmitted",
    "Tr Commissions":"trCommissions",
    "Total Amount Claimed":"totalAmountClaimed",
    "Total Amount Settled":"totalAmountSettled",
    "Total Amount Rejected":"totalAmountRejected",
    "Ring central Sms Response":"ringcentralSmsResponse",
    "Medical Confirmation No":"medicalConfirmationNo",
    "M Appointment Date":"mAppointmentDate",
    "Amount Settled":"AmountSettled",
    "Claim Closed On":"claimClosedOn",
    "Rejection Observations":"rejectionObservations",
    "Policy Renewal Completed":"policyRenewalCompleted",
    "Policy Review Comments":"policyReviewComments",
    "Policy Review Comment Updated On":"policyReviewCommentUpdatedOn",
    "Claim Outcome":"claimOutcome",
    "Renewal Medical Application Date And Time":"renewalMedicalApplicationDateAndTime",
    "Reason For Policy Being Declined":"reasonForPolicyBeingDeclined",
    "Reviewed Date":"reviewedDate",
    "Renewal Medical Requirement":"renewalMedicalRequirement",
    "New Policy Start Date":"newPolicyStartDate",
    "Application Initiated On":"applicationInitiatedOn",
    "Policy Attachment Link":"policyAttachmentLink",
    "Name Of Confirmation Renewal":"nameOfConfirmationRenewal",
    "Name Of Confirmation":"nameOfConfirmation",
    "Cancellation":"cancellation",
    "Renwal Expired":"renwalExpired",
    "Confirmation Policy Start":"confirmationPolicyStart",
    "Are Current Claim on This Policy":"areCurrentClaimonThisPolicy",
    "Are Past Claim on This Policy":"arePastClaimonThisPolicy",
    "Reviewed Date Time":"reviewedDateTime",
    "Corporate Policy Commission Amount":"corporatePolicyCommissionAmount"
};

const policyOwnership = {
    "Policy ID":"policyId",
    "Name":"name",
    "DOB":"dob",
    "Email":"email",
    "Phone":"phone",
    "Relationship":"relationship"
};

module.exports = {
    policies,
    policyCommission,
    supervisaPolicySubDetails,
    policySubDetails,
    policyOwnership
};