module.exports = {
  leadsDetails: {
    leads: {
      sourceId: null,
      leadStatus: "new",
      eligibleRoundRobinOwnerFound: true,
      existingInsurancePolicy: "Yes",
      genderPrediction: "Yes",
      source: "catalyst",
      leadStatusStage: "Not Contacted",
      understandingOfInsurance: "Expert",
      phoneBurnerLastCallTime: "{}",
      layoutName: "Client",
      preferredContactTime: null,
      vehicleYear: "Vehicle Year",
      quote: "Quote",
      genderPredictionScore: "1",
      exchangeRate: "34",
      insuranceLeadSource: "Canadian LIC Website",
      insuranceLeadOwner: "22106000000065307",
      additionalContactInformation: "Available",
      celebratedFestivals: "Victoria Day",
      socialMediaInformation: "Available",
      whenWasYourVehicleMade: "When Was Your Vehicle Made?",
      emailIsValid: "Yes",
      nextFollowUpDateTime: "{}",
      isThisaReassignment: "Yes",
      areYouLLQPLicensed: "Are You LLQP Licensed?",
      doYouOwnaHomeInCanada: "",
      addEmail1: "peter@gmail.com",
      childAge: "2",
      insuranceLeadStatus: "Not Contacted",
      firstName: "Peter",
      areYouReadyToPurchaseThisLifeInsurancePol: true,
      phoneNumber: "741852963",
      preferredContactMethod: "Home Phone",
      name: "Peter",
      deposit: "Deposit",
      leadCreatedOn: "2024-08-15",
      CREATEDTIME: "2024-08-28 13:50:11:642",
      reRunRoundRobin: null,
      whatsapp: "6666666",
      driverLicenseNo: "Driver License No",
      lastName: "Anotny",
      gender: "Male",
      whereWouldYouBeTravellingto: "Where would you be travelling to",
      rcSmsOptOut: null,
      areYouReadyToPurchaseThisLifeInsurancePoli:
        "Are you ready to purchase this Life Insurance Poli",
      dateOfBirthOfTraveler: "2024-08-27",
      emailOptOut: true,
      phoneBurnerLastCallOutcome: "PhoneBurner Last Call Outcome",
      bestTimeToCall: "Best Time to Call",
      doYouhaveLifeInsurance: "",
      startDateOfCoverage: null,
      currency: "USD",
      assignedAdvisor: "22106000000346824",
      email: "peterj@trigya.co",
      inboxURL: "",
      CREATORID: "22106000000035019",
      emailRoundRobinOwner: true,
      howMuchAmountWantToStartWith: "85",
      phoneBurnerFollowUpDate: "2024-08-30",
      locationName: "22106000000376178",
      submitPageURL: "",
      whatIsYourPostalCode: "What Is Your Po",
      mobile: "777777",
      dateOfBirth: "2024-08-23",
      religion: "Islam",
      removeFromCampaign: true,
      citizenshipStatus: "Canadian Citizenship",
      oldDatabaseLead: "",
      MODIFIEDTIME: "2024-08-28 13:50:11:642",
      whattypeofStudent: "International Students in Canada",
      tripType: "Multiple Trip",
      referredBy: "External Referral",
      netWorth: "Yes",
      assignedCampaigns: "",
      roundRobinProcessed: true,
      howMuchYouLikeToStartThePlan: "How Much You Like to Start the Plan?",
      ROWID: "22106000000446931",
      dateOfBirth1: "2024-08-30",
      roundRobinAssignmentTime: "{}",
      leadID: null,
    },
    leadsDescription: {
      coverageYouAreLookingFor: "333",
      whatsYourProfession: "",
      areYouLookingForDrugAndDentalOrJustDrugPla: "33",
      howManyChildrensDoYouHave: "3",
      oneMillionInAnTfsaAccountAtRetirement: "",
      whatsYourAge: "3",
      existingHealthConditions: "",
      enterageOf2ndTraveler: "",
      whatTypeOfTermPlanAreYouLookingFor: "33",
      areYouLicensedAsAnInsuranceAdvisor: "Yes",
      selectTheDurationOfTheCoverage: "",
      wouldYouLikeToKnowHowSuperVisaInsuranceWo: "",
      qualifyFor15BonusOfYourRespAccount: null,
      enterTheAmountOfMortgageCoverageRequired: "333",
      leadId: "22106000000446931",
      whatPolicyDoYouWant: "3",
      previousPolicyWithUs: "",
      preExistingmedicaLconditions: "3",
      secureYourChildFutureWithHigherEducation: "",
      wouldYouLikeToKnowHowRespWorks: "",
      gclidField: null,
      LookingForAdvisor: null,
      doYouWantCriticalIllnessInsuranceWithMoney: "3",
      coverageForDrugAndDentalCost: null,
      whatKindOfBusinesssIsIt: "3",
      totalDependents: null,
      doYouHaveAnyMedicalIssue: "33",
      growthOnYourInvestmentInRespAccount: null,
      CREATEDTIME: "2024-08-28 13:50:12:694",
      howMuchMonthlyBenefitDoYouNeed: "3",
      youAreSeekingCoverageFor: "3",
      prescriptionMedicationCoverage: null,
      secureYourChildsFutureWithHigherEducation: "33",
      typeOfInsuranceLooking: "Type of Insurance Looking",
      howLongDoYouNeedCoverageFor: "3",
      areYouAnOwnerOrEmployeeOfTheBusiness: "33",
      whatTimeFrameYouLikeToMoveToBeaAdvisor: "3 Months",
      wouldYouLikeToKnowHowRrspWorks: "",
      whatIsYourResidencyStatusInCanada: "3",
      superVisaInsurance: "",
      monthlyPremiumKnowledge: "",
      moneyRequireToCompleteYourChildEducation: "3",
      doYouWanToDepositMonthlyOrYearlyPremium: "33",
      singleOrFamilyPlan: "",
      tobaccoused: "33",
      CREATORID: "22106000000035019",
      depositEveryMonthTowardsYourChildEducation: "33",
      canYouPleaseLetMeKnowPremiumPaymentMode: "3",
      howMuchCoverageIsRequired: "333",
      wouldLikeToIncreaseMonthlyDeposits: "3",
      selectYourAgeBracket: "3",
      ageOf1stTraveler: "33",
      respAccountsForYourChildChildrens: null,
      wouldYouLikeToKnowHowTfsaWorks: "",
      whatageDoYouWanttostartTheWithdrawalFrom: "33",
      MODIFIEDTIME: "2024-08-28 13:50:12:694",
      howManyCriticalIllnessCoverageYouNeed: "333",
      moneyRequireToCompleteYourChildsEducation: null,
      travelerStartDate: "2024-08-31",
      howDoYouConsiderYourHealth: "33",
      eligibleToGetExtra2000InGovernmentGrants: "33",
      oneMillionInanRespAccountAtRetirement: "33",
      howMuchdoYouWantToSaveYearly: "3",
      travelerEndDate: "2024-08-30",
      howMuchDoYouWantToSaveMonthly: "3",
      ROWID: "22106000000458195",
    },
    leadService: {
      adgroupidData: "33",
      investments: "RIF",
      groupInsurance: "Group Life",
      combinationOrHybridInsurance: true,
      healthAndDentalInsurance: "true",
      travelInsurance: "Travel",
      immigrationServices: "Builder's Risk Insurance",
      homeInsurance: "Condo Insurance",
      matchtypeData: "33",
      leadId: "22106000000446931",
      CREATORID: "22106000000035019",
      keywordData: "33",
      campaignidData: "33",
      deviceData: "33",
      livingBenefits: "Disability - Accidental",
      autoInsurance: "Auto Insurance",
      MODIFIEDTIME: "2024-08-28 13:50:13:059",
      loanProtection: "Rent Insurance",
      servicesRequested: "Health & Dental Insurance",
      networkData: "33",
      lifeInsurance: "Permanent Universal Life",
      businessLiabilityInsurance: "Builder's Risk Insurance",
      potentialBusiness: "22222",
      gclidData: "33",
      CREATEDTIME: "2024-08-28 13:50:13:059",
      lpUrlData: "33",
      ROWID: "22106000000446934",
    },
    familyTree: {
      dependentParents: "Yes",
      siblings: "Yes",
      nameOfCommonLawPartner: "",
      advisorId: null,
      dealId: null,
      emergencyContactRelationship: null,
      nameOfSpouse: "3333",
      emergencyContactEmail: null,
      leadId: "22106000000446931",
      CREATORID: "22106000000035019",
      numberOfDependentParents: "3",
      contactId: null,
      emergencyinfo: false,
      emergencyContactName: null,
      numberOfSiblings: "3",
      spouseDateOfBirth: "2024-09-06",
      numberOfDependentChildren: "3",
      emergencyContactPhone: null,
      MODIFIEDTIME: "2024-08-28 13:50:12:003",
      anniversaryDate: "2024-08-30",
      phoneOfSpouse: "33",
      dependentChildren: "Yes",
      commonLawDateOfBirth: "",
      CREATEDTIME: "2024-08-28 13:50:12:003",
      emailOfSpouse: "333",
      ROWID: "22106000000449976",
      relationShipStatus: "Married",
      numberOfSpouse: "33",
    },
    leadInformations: {
      country: "333",
      zipCode: "333",
      coverageYouAreLookingFor: null,
      databaseLead1: null,
      insuranceLeadsScoringScore: null,
      year: null,
      investments1: null,
      citizenshipStatus1: null,
      insurenceLeadsScoringPositiveTouchPointScore: null,
      isthisAReassignment: null,
      ifreferredbyAdvisor: null,
      referralSource: null,
      insurenceLeadsScoringNegativeScore: null,
      contact: null,
      adSetId: "33",
      additionalContactInformation: null,
      existingPolicyRenewalDueBy: null,
      state: "333",
      roundRobinAssignmentTime1: null,
      oldDatabaseLead1: null,
      existingInsurancePolicy2: null,
      leadId: "22106000000446931",
      doYouOwnAHomeInCanada: null,
      insurenceLeadsScoringNegativeTouchPointScore: null,
      contactId: null,
      facebookPage: "333",
      adAccountId: "33",
      gender1: null,
      adCampaignId: "333",
      insuranceLeadScoringNegativeScore: null,
      linkedIn1: null,
      facebookAd: "333",
      insuranceLeadScoringPositiveTouchPointScore: null,
      genderPrediction1: null,
      networth2: null,
      adId: "333",
      insuranceLeadScoringTouchPointScore: null,
      doYouHavelifeInsurance: null,
      productCategoryReferred: null,
      facebook1: null,
      adSet: "333",
      CREATEDTIME: "2024-08-28 13:50:12:346",
      insuranceLeadScoringNegativeTouchPointScore: null,
      leadForm: "3333",
      adCampaign: "33",
      referralOtherThanClient: null,
      city: "333",
      costPerLead: "333",
      twitter1: null,
      bestTimeToCall: null,
      facebookPageId: "33",
      street: "33",
      facebookAdInformation: "Available",
      instagram1: null,
      referralClient: null,
      insurenceLeadsScoringPositiveScore: null,
      CREATORID: "22106000000035019",
      insuranceLeadScoringPositiveScore: null,
      submitPageURL: null,
      adAccount: "33",
      preferredContactTime2: null,
      preferredContactMethod2: null,
      skypeId: null,
      MODIFIEDTIME: "2024-08-28 13:50:12:346",
      currency1: null,
      servicesRequested: null,
      exchangeRate1: null,
      understandingOfInsurance1: null,
      referredBy: null,
      linkdin1: null,
      instagramId: null,
      assignedCampaigns: null,
      leadFormId: "333",
      leadCreatedOn1: null,
      ROWID: "22106000000452827",
      dateOfBirth1: null,
    },
    dependentChildrenData: [
      {
        CREATORID: "22106000000035019",
        contactId: null,
        dealId: null,
        MODIFIEDTIME: "2024-08-28 13:50:13:375",
        phone: "6",
        dob: "2024-09-05",
        name: "6",
        CREATEDTIME: "2024-08-28 13:50:13:375",
        relationship: "6",
        ROWID: "22106000000452830",
        email: "6",
        age: "6",
        leadId: "22106000000446931",
      },
    ],
    dependentParentsData: [
      {
        CREATORID: "22106000000035019",
        contactId: null,
        dealId: null,
        MODIFIEDTIME: "2024-08-28 13:50:13:674",
        phone: "5",
        dob: "2024-08-30",
        name: "5",
        CREATEDTIME: "2024-08-28 13:50:13:674",
        relationship: "5",
        ROWID: "22106000000458198",
        email: "5",
        age: "5",
        leadId: "22106000000446931",
      },
    ],
    siblingData: [
      {
        CREATORID: "22106000000035019",
        contactId: null,
        dealId: null,
        MODIFIEDTIME: "2024-08-28 13:50:13:975",
        phone: "7",
        dob: "2024-09-06",
        name: "7",
        CREATEDTIME: "2024-08-28 13:50:13:975",
        relationship: "7",
        ROWID: "22106000000446937",
        email: "7",
        age: "7",
        leadId: "22106000000446931",
      },
    ],
    emergencyContactData: [
      {
        CREATORID: "22106000000035019",
        emergencyContactPhone: "1",
        MODIFIEDTIME: "2024-08-28 13:50:14:281",
        contactId: null,
        emergencyContactName: "1",
        dealId: null,
        emergencyContactRelationship: "1",
        emergencyContactEmail: "1",
        CREATEDTIME: "2024-08-28 13:50:14:281",
        ROWID: "22106000000449979",
        leadId: "22106000000446931",
      },
    ],
    festivalsData: [
      {
        CREATORID: "22106000000035019",
        MODIFIEDTIME: "2024-08-28 13:50:14:892",
        contactId: null,
        dateOfFestival: "2024-08-30",
        dealId: null,
        festivalName: "Lohri",
        CREATEDTIME: "2024-08-28 13:50:14:892",
        ROWID: "22106000000458201",
        leadId: "22106000000446931",
      },
      {
        CREATORID: "22106000000035019",
        MODIFIEDTIME: "2024-08-28 13:50:14:895",
        contactId: null,
        dateOfFestival: "2024-08-30",
        dealId: null,
        festivalName: "Father's Day",
        CREATEDTIME: "2024-08-28 13:50:14:895",
        ROWID: "22106000000458203",
        leadId: "22106000000446931",
      },
    ],
    LeadData: [
      {
        CREATORID: "22106000000035019",
        comments: "4",
        contactId: null,
        timeSpent: "4",
        dealId: null,
        timeOfInteraction: "2024-08-30T10:20",
        interactionOutcome: "4",
        probabilityOfClosure: "4",
        MODIFIEDTIME: "2024-08-28 13:50:14:592",
        interactionType: "Call",
        dateOfInteraction: null,
        contactAttempt: "44",
        CREATEDTIME: "2024-08-28 13:50:14:592",
        ROWID: "22106000000452833",
        leadId: "22106000000446931",
      },
      {
        CREATORID: "22106000000035019",
        comments: "4",
        contactId: null,
        timeSpent: "4",
        dealId: null,
        timeOfInteraction: "2024-08-29T10:20",
        interactionOutcome: "4",
        probabilityOfClosure: "4",
        MODIFIEDTIME: "2024-08-28 13:50:14:594",
        interactionType: "Call",
        dateOfInteraction: null,
        contactAttempt: "1",
        CREATEDTIME: "2024-08-28 13:50:14:594",
        ROWID: "22106000000452835",
        leadId: "22106000000446931",
      },
    ],
  },
  leadAdvisor: {
    leads: {
      sourceId: null,
      leadStatus: "new",
      coverageYouAreLookingFor: "2",
      eligibleRoundRobinOwnerFound: true,
      existingInsurancePolicy: "Yes",
      genderPrediction: "Unknown",
      source: "catalyst",
      leadStatusStage: "Create Deal",
      understandingOfInsurance: "Expert",
      phoneBurnerLastCallTime: null,
      layoutName: "Client",
      preferredContactTime: null,
      vehicleYear: "",
      quote: "",
      genderPredictionScore: "",
      exchangeRate: "2",
      readyForPurchase: "true",
      insuranceLeadSource: "Advisor Generated",
      insuranceLeadOwner: "22106000000065307",
      additionalContactInformation: "Available",
      celebratedFestivals: "New Year",
      socialMediaInformation: "Unavailable",
      existingPolicyRenewalDueBy: "2024-08-22",
      fax: "2222222",
      whenWasYourVehicleMade: "",
      emailIsValid: "",
      nextFollowUpDateTime: "{}",
      isThisaReassignment: "22106000000415467",
      areYouLLQPLicensed: "Are You LLQP Licensed",
      doYouOwnaHomeInCanada: "Yes",
      addEmail1: "",
      childAge: "",
      insuranceLeadStatus: "",
      ifReferredByAdvisorOrExternalReferral: "Yes",
      firstName: "Peter",
      areYouReadyToPurchaseThisLifeInsurancePol: null,
      phoneNumber: "9047090872",
      preferredContactMethod: "Cell Phone",
      name: "",
      deposit: "",
      leadCreatedOn: null,
      CREATEDTIME: "2024-08-29 17:27:13:410",
      reRunRoundRobin: true,
      whatsapp: "",
      driverLicenseNo: "",
      lastName: "AnotnyDEMO",
      secondaryEmail: "222",
      gender: "Unknown",
      whereWouldYouBeTravellingto: "",
      rcSmsOptOut: true,
      description: "sdbdgsnbsfgnsf",
      areYouReadyToPurchaseThisLifeInsurancePoli: "2",
      dateOfBirthOfTraveler: null,
      emailOptOut: false,
      phoneBurnerLastCallOutcome: "",
      bestTimeToCall: "",
      doYouhaveLifeInsurance: "",
      startDateOfCoverage: null,
      currency: "CAD",
      assignedAdvisor: "22106000000415464",
      email: "info@admin.co",
      inboxURL: " Inbox URL",
      CREATORID: "22106000000035019",
      emailRoundRobinOwner: null,
      howMuchAmountWantToStartWith: "",
      phoneBurnerFollowUpDate: null,
      locationName: "22106000000376178",
      submitPageURL: " Submit Page URL",
      whatIsYourPostalCode: "",
      mobile: "987654321",
      dateOfBirth: "2024-08-24",
      religion: "Buddhism",
      removeFromCampaign: false,
      citizenshipStatus: "PR",
      oldDatabaseLead: "Yes",
      MODIFIEDTIME: "2024-08-29 17:27:13:410",
      whattypeofStudent: "",
      tripType: "",
      referredBy: "Lead/Client",
      netWorth: "Expert",
      assignedCampaigns: "Assigned Campaigns",
      roundRobinProcessed: true,
      howMuchYouLikeToStartThePlan: "",
      ROWID: "22106000000468012",
      dateOfBirth1: null,
      roundRobinAssignmentTime: "{}",
      leadID: "",
    },
    leadsDescription: {
      coverageYouAreLookingFor: null,
      whatsYourProfession: null,
      areYouLookingForDrugAndDentalOrJustDrugPla: null,
      howManyChildrensDoYouHave: null,
      oneMillionInAnTfsaAccountAtRetirement: null,
      whatsYourAge: null,
      existingHealthConditions: null,
      enterageOf2ndTraveler: null,
      whatTypeOfTermPlanAreYouLookingFor: null,
      areYouLicensedAsAnInsuranceAdvisor: null,
      selectTheDurationOfTheCoverage: null,
      wouldYouLikeToKnowHowSuperVisaInsuranceWo: null,
      qualifyFor15BonusOfYourRespAccount: null,
      enterTheAmountOfMortgageCoverageRequired: null,
      leadId: null,
      whatPolicyDoYouWant: null,
      previousPolicyWithUs: null,
      preExistingmedicaLconditions: null,
      secureYourChildFutureWithHigherEducation: null,
      wouldYouLikeToKnowHowRespWorks: null,
      gclidField: null,
      LookingForAdvisor: null,
      doYouWantCriticalIllnessInsuranceWithMoney: null,
      coverageForDrugAndDentalCost: null,
      whatKindOfBusinesssIsIt: null,
      totalDependents: null,
      doYouHaveAnyMedicalIssue: null,
      growthOnYourInvestmentInRespAccount: null,
      CREATEDTIME: null,
      howMuchMonthlyBenefitDoYouNeed: null,
      youAreSeekingCoverageFor: null,
      prescriptionMedicationCoverage: null,
      secureYourChildsFutureWithHigherEducation: null,
      typeOfInsuranceLooking: null,
      howLongDoYouNeedCoverageFor: null,
      areYouAnOwnerOrEmployeeOfTheBusiness: null,
      whatTimeFrameYouLikeToMoveToBeaAdvisor: null,
      wouldYouLikeToKnowHowRrspWorks: null,
      whatIsYourResidencyStatusInCanada: null,
      superVisaInsurance: null,
      monthlyPremiumKnowledge: null,
      moneyRequireToCompleteYourChildEducation: null,
      doYouWanToDepositMonthlyOrYearlyPremium: null,
      singleOrFamilyPlan: null,
      tobaccoused: null,
      CREATORID: null,
      depositEveryMonthTowardsYourChildEducation: null,
      canYouPleaseLetMeKnowPremiumPaymentMode: null,
      howMuchCoverageIsRequired: null,
      wouldLikeToIncreaseMonthlyDeposits: null,
      selectYourAgeBracket: null,
      ageOf1stTraveler: null,
      respAccountsForYourChildChildrens: null,
      wouldYouLikeToKnowHowTfsaWorks: null,
      whatageDoYouWanttostartTheWithdrawalFrom: null,
      MODIFIEDTIME: null,
      howManyCriticalIllnessCoverageYouNeed: null,
      moneyRequireToCompleteYourChildsEducation: null,
      travelerStartDate: null,
      howDoYouConsiderYourHealth: null,
      eligibleToGetExtra2000InGovernmentGrants: null,
      oneMillionInanRespAccountAtRetirement: null,
      howMuchdoYouWantToSaveYearly: null,
      travelerEndDate: null,
      howMuchDoYouWantToSaveMonthly: null,
      ROWID: null,
    },
    leadService: {
      adgroupidData: "",
      investments: "Mutual Funds",
      groupInsurance: "Rent Insurance",
      combinationOrHybridInsurance: true,
      healthAndDentalInsurance: "true",
      travelInsurance: "Travel",
      immigrationServices: null,
      homeInsurance: "",
      matchtypeData: "",
      leadId: "22106000000468012",
      CREATORID: "22106000000035019",
      keywordData: "",
      campaignidData: "",
      deviceData: "",
      livingBenefits: "Disability - Accidental",
      autoInsurance: "",
      MODIFIEDTIME: "2024-08-29 17:43:55:505",
      loanProtection: "Rent Insurance",
      servicesRequested: "Home Insurance",
      networkData: "",
      lifeInsurance: "Permanent Universal Life",
      businessLiabilityInsurance: null,
      potentialBusiness: null,
      gclidData: "",
      CREATEDTIME: "2024-08-29 17:43:55:505",
      lpUrlData: "",
      ROWID: "22106000000460942",
    },
    familyTree: {
      dependentParents: "Yes",
      siblings: "Yes",
      nameOfCommonLawPartner: "",
      advisorId: null,
      dealId: null,
      emergencyContactRelationship: null,
      nameOfSpouse: "rr",
      emergencyContactEmail: null,
      depParents: "[Father]",
      leadId: "22106000000468012",
      CREATORID: "22106000000035019",
      numberOfDependentParents: "3",
      contactId: null,
      emergencyinfo: false,
      emergencyContactName: null,
      numberOfSiblings: "2",
      spouseDateOfBirth: "2024-08-24",
      depChildren: "[Daughter]",
      depSiblings: "[Sister]",
      numberOfDependentChildren: "2",
      emergencyContactPhone: null,
      MODIFIEDTIME: "2024-08-29 17:29:58:198",
      anniversaryDate: "2024-08-31",
      phoneOfSpouse: "333",
      dependentChildren: "Yes",
      commonLawDateOfBirth: "",
      CREATEDTIME: "2024-08-29 17:29:58:198",
      emailOfSpouse: "3",
      ROWID: "22106000000465939",
      relationShipStatus: "Married",
      numberOfSpouse: "3",
    },
    leadInformations: {
      country: "e",
      zipCode: "e",
      coverageYouAreLookingFor: null,
      databaseLead1: null,
      insuranceLeadsScoringScore: null,
      year: "2021",
      investments1: null,
      citizenshipStatus1: null,
      insurenceLeadsScoringPositiveTouchPointScore: null,
      isthisAReassignment: null,
      ifreferredbyAdvisor: null,
      referralSource: "Client",
      insurenceLeadsScoringNegativeScore: null,
      contact: null,
      adSetId: "",
      additionalContactInformation: null,
      existingPolicyRenewalDueBy: null,
      state: "e",
      roundRobinAssignmentTime1: null,
      oldDatabaseLead1: null,
      existingInsurancePolicy2: null,
      leadId: "22106000000468012",
      doYouOwnAHomeInCanada: null,
      insurenceLeadsScoringNegativeTouchPointScore: null,
      contactId: null,
      facebookPage: "",
      adAccountId: "e",
      gender1: null,
      adCampaignId: "e",
      insuranceLeadScoringNegativeScore: null,
      linkedIn1: "e",
      facebookAd: "e",
      insuranceLeadScoringPositiveTouchPointScore: null,
      genderPrediction1: null,
      networth2: null,
      adId: "e",
      insuranceLeadScoringTouchPointScore: null,
      doYouHavelifeInsurance: null,
      productCategoryReferred: "Life",
      adSet: "e",
      CREATEDTIME: "2024-08-29 17:29:58:514",
      insuranceLeadScoringNegativeTouchPointScore: null,
      leadForm: "e",
      adCampaign: "e",
      referralOtherThanClient: null,
      city: "e",
      costPerLead: "e",
      twitter1: null,
      bestTimeToCall: null,
      facebookPageId: "",
      street: "ee",
      facebookAdInformation: "",
      instagram1: null,
      referralClient: null,
      insurenceLeadsScoringPositiveScore: null,
      CREATORID: "22106000000035019",
      insuranceLeadScoringPositiveScore: null,
      submitPageURL: null,
      adAccount: "e",
      preferredContactTime2: null,
      preferredContactMethod2: null,
      skypeId: "e",
      MODIFIEDTIME: "2024-08-29 17:29:58:514",
      currency1: null,
      servicesRequested: null,
      exchangeRate1: null,
      faceBook: "e",
      understandingOfInsurance1: null,
      referredBy: null,
      linkdin1: null,
      instagramId: "e",
      assignedCampaigns: null,
      leadFormId: "e",
      leadCreatedOn1: null,
      ROWID: "22106000000465942",
      dateOfBirth1: null,
    },
    dependentChildrenData: [
      {
        CREATORID: "22106000000035019",
        contactId: null,
        dealId: null,
        MODIFIEDTIME: "2024-08-29 17:47:36:791",
        phone: "3",
        dob: "2024-09-03",
        name: "3",
        CREATEDTIME: "2024-08-29 17:47:36:791",
        relationship: "3",
        ROWID: "22106000000467092",
        email: "3",
        age: "3",
        leadId: "22106000000468012",
      },
    ],
    dependentParentsData: [
      {
        CREATORID: "22106000000035019",
        contactId: null,
        dealId: null,
        MODIFIEDTIME: "2024-08-29 17:47:37:135",
        phone: "3",
        dob: "2024-08-28",
        name: "3",
        CREATEDTIME: "2024-08-29 17:47:37:135",
        relationship: "2",
        ROWID: "22106000000468057",
        email: "3",
        age: "3",
        leadId: "22106000000468012",
      },
    ],
    siblingData: [
      {
        CREATORID: "22106000000035019",
        contactId: null,
        dealId: null,
        MODIFIEDTIME: "2024-08-29 17:47:37:441",
        phone: "3",
        dob: "2024-09-06",
        name: "3",
        CREATEDTIME: "2024-08-29 17:47:37:441",
        relationship: "3",
        ROWID: "22106000000465978",
        email: "3",
        age: "3",
        leadId: "22106000000468012",
      },
    ],
    emergencyContactData: [
      {
        CREATORID: "22106000000035019",
        emergencyContactPhone: "3",
        MODIFIEDTIME: "2024-08-29 17:47:37:747",
        contactId: null,
        emergencyContactName: "3",
        dealId: null,
        emergencyContactRelationship: "3",
        emergencyContactEmail: "3",
        CREATEDTIME: "2024-08-29 17:47:37:747",
        ROWID: "22106000000460948",
        leadId: "22106000000468012",
      },
    ],
    festivalsData: [
      {
        CREATORID: "22106000000035019",
        MODIFIEDTIME: "2024-08-29 17:47:38:349",
        contactId: null,
        dateOfFestival: "2024-08-16",
        dealId: null,
        festivalName: "New Year",
        CREATEDTIME: "2024-08-29 17:47:38:349",
        ROWID: "22106000000465981",
        leadId: "22106000000468012",
      },
    ],
    LeadData: [
      {
        CREATORID: "22106000000035019",
        comments: "2",
        contactId: null,
        timeSpent: "2",
        dealId: null,
        timeOfInteraction: "2024-08-08T12:15",
        interactionOutcome: "2",
        probabilityOfClosure: "2",
        MODIFIEDTIME: "2024-08-29 17:47:38:049",
        interactionType: "Call",
        dateOfInteraction: null,
        contactAttempt: "2",
        CREATEDTIME: "2024-08-29 17:47:38:049",
        ROWID: "22106000000468060",
        leadId: "22106000000468012",
      },
    ],
  },
  users: [
    {
      firstName: "trigya",
      lastName: "info",
      name: "trigya info",
      ROWID: "22106000000065307",
    },
    {
      firstName: "test",
      lastName: "trigya",
      name: "test trigya",
      ROWID: "22106000000158085",
    },
  ],
  locations: [
    {
      name: "location name update",
      ROWID: "22106000000376178",
    },
  ],
  leads: [
    {
      firstName: "Macy",
      lastName: "Gould",
      name: "Macy Gould",
      ROWID: "22106000000322869",
    },
    {
      firstName: "Ciara",
      lastName: "Luna",
      name: "Ciara Luna",
      ROWID: "22106000000341005",
    },
    {
      firstName: "advisor",
      lastName: "test",
      name: "advisor test",
      ROWID: "22106000000343903",
    },
    {
      firstName: "shobhnath ",
      lastName: "test",
      name: "shobhnath  test",
      ROWID: "22106000000346537",
    },
    {
      firstName: "first name",
      lastName: "last name ",
      name: "first name last name ",
      ROWID: "22106000000348490",
    },
    {
      firstName: "Olivia",
      lastName: "Leon",
      name: "Olivia Leon",
      ROWID: "22106000000348503",
    },
    {
      firstName: "test ",
      lastName: "email",
      name: "test  email",
      ROWID: "22106000000348721",
    },
    {
      firstName: "Peter",
      lastName: "Anotny Client",
      name: "Peter Anotny Client",
      ROWID: "22106000000353109",
    },
    {
      firstName: "Peter",
      lastName: "Anotny Advisor",
      name: "Peter Anotny Advisor",
      ROWID: "22106000000353173",
    },
    {
      firstName: "shobhnath test",
      lastName: "",
      name: "shobhnath test ",
      ROWID: "22106000000386371",
    },
    {
      firstName: "Chaney",
      lastName: "Dennis",
      name: "Chaney Dennis",
      ROWID: "22106000000386391",
    },
  ],
  advisors: [
    {
      firstName: "shobhnath ",
      lastName: "test",
      name: "shobhnath  test",
      ROWID: "22106000000346824",
    },
  ],
};
