// Sample data for generating CSV

module.exports = [
    {
      insuranceLeadOwner: "John Doe",
      insuranceLeadSource: "Referral",
      firstName: "John",
      lastName: "Doe",
      mobile: "123-456-7890",
      areYouLLQPLicensed: true,
      email: "john.doe@example.com",
      leadStatusStage: "Initial Contact",
      dateOfBirth: "1985-05-15",
      assignedAdvisor: "Jane Smith",
      gender: "Male",
      isThisaReassignment: false,
      locationName: "New York",
      ifReferredByAdvisorOrExternalReferral: "Michael Johnson",
      netWorth: "$500,000",
      referredBy: "Existing Client",
      exchangeRate: "1.25",
      preferredContactMethod: "Email",
      currency: "USD",
      preferredContactTime: "Morning",
      socialMediaInformation: "Facebook: JohnDoe",
      roundRobinAssignmentTime: "2024-01-01T09:00:00Z",
      citizenshipStatus: "US Citizen",
      understandingOfInsurance: "High",
      existingInsurancePolicy: "Yes",
      oldDatabaseLead: false,
      doYouOwnaHomeInCanada: false,
      genderPredictionScore: 0.85,
      doYouhaveLifeInsurance: true,
      rcSmsOptOut: false,
      coverageYouAreLookingFor: "Comprehensive",
      areYouReadyToPurchaseThisLifeInsurancePoli: true,
      nextFollowUpDateTime: "2024-01-15T10:00:00Z",
      areYouReadyToPurchaseThisLifeInsurancePol: true,
      additionalContactInformation: "Secondary phone: 987-654-3210",
      submitPageURL: "http://example.com/submit",
      assignedCampaigns: "Campaign 1",
      genderPrediction: "Male",
      inboxURL: "http://example.com/inbox",
      phoneNumber: "123-456-7890",
      secondaryEmail: "john.doe@altmail.com",
      fax: "123-456-7891",
      roundRobinProcessed: true,
      emailRoundRobinOwner: true,
      eligibleRoundRobinOwnerFound: true,
      reRunRoundRobin: false,
      readyForPurchase: true,
      description: "High priority lead",
      relationShipStatus: "Married",
      dependentParents: "Yes",
      dependentChildren: "Yes",
      siblings: "Yes",
      emergencyContact: "Jane Doe",
      street: "123 Elm St",
      state: "NY",
      country: "USA",
      city: "New York",
      zipCode: "10001",
      year: "2024",
      referralClient: "Client A",
      referralSource: "Internet",
      referralOtherThanClient: "Social Media",
      productCategoryReferred: "Life Insurance",
      adAccount: "Account123",
      adSet: "Set456",
      adAccountId: "789123",
      adSetId: "456789",
      adCampaign: "Campaign ABC",
      facebookAd: "Ad XYZ",
      adCampaignId: "321654",
      adId: "987654",
      facebookPage: "John's Insurance",
      leadForm: "Form 1",
      facebookPageId: "Page001",
      leadFormId: "Form001",
      costPerLead: "$10",
      facebookAdInformation: "High Engagement",
      twitter1: "@JohnDoe",
      linkedIn1: "john-doe",
      skypeId: "john.doe",
      faceBook: "John Doe",
      instagramId: "@johndoe",
      religion: "Christian",
      celebratedFestivals: "Christmas, Easter",
      importantFestivalsDates: "Christmas: 2024-12-25",
      leadManagementHistory: "Initial contact made on 2024-01-01",
      potentialBusiness: "$100,000",
      loanProtection: "Yes",
      servicesRequested: "Life Insurance, Investments",
      investments: "$50,000",
      lifeInsurance: "Term Life",
      groupInsurance: "Yes",
      livingBenefits: "Critical Illness Coverage",
      travelInsurance: "Yes",
      combinationOrHybridInsurance: "Yes",
      healthAndDentalInsurance: "Yes",
    },
    // Add more rows as needed
  ];
  
  