// Sample data for generating CSV
module.exports = [
    {
      insuranceLeadOwner: "Alice Johnson",
      insuranceLeadSource: "Website",
      firstName: "Alice",
      lastName: "Johnson",
      mobile: "555-1234",
      insuranceLeadStatus: "New",
      whatsapp: "555-5678",
      leadStatusStage: "Initial",
      email: "alice.johnson@example.com",
      assignedAdvisor: "Bob Smith",
      emailIsValid: true,
      removeFromCampaign: false,
      emailOptOut: false,
      dateOfBirth: "1990-02-15",
      bestTimeToCall: "Morning",
      gender: "Female",
      referredBy: "Referral Program",
      isThisaReassignment: false,
      locationName: "Los Angeles",
      netWorth: "750000",
      preferredContactMethod: "Email",
      socialMediaInformation: "LinkedIn: alicejohnson",
      currency: "USD",
      exchangeRate: "1.0",
      preferredContactTime: "Afternoon",
      citizenshipStatus: "US Citizen",
      understandingOfInsurance: "Intermediate",
      roundRobinProcessed: true,
      emailRoundRobinOwner: false,
      eligibleRoundRobinOwnerFound: true,
      reRunRoundRobin: false,
      roundRobinAssignmentTime: "2024-01-02T14:00:00Z",
      existingInsurancePolicy: "Yes",
      doYouOwnAhomeInCanada: "No",
      leadCreatedOn: "2024-01-01",
      nextFollowUpDateTime: "2024-01-10T09:00:00Z",
      doYouHaveLifeInsurance: "Yes",
      oldDatabaseLead: false,
      genderPredictionScore: 0.9,
      submitPageURL: "http://example.com/submit",
      assignedCampaigns: "Campaign 2",
      areYouReadyToPurchaseThisLifeInsurancePoli: true,
      genderPrediction: "Female",
      inboxURL: "http://example.com/inbox",
      areYouReadyToPurchaseThisLifeInsurancePol: true,
      additionalContactInformation: "Alternate phone: 555-8765",
      phoneBurnerLastCallOutcome: "Left Voicemail",
      areYouLLQPLicensed: true,
      phoneBurnerFollowUpDate: "2024-01-11T10:00:00Z",
      phoneBurnerLastCallTime: "2024-01-09T11:30:00Z",
      driverLicenseNo: "D1234567",
      vehicleYear: "2018",
      whatIsYourPostalCode: "90001",
      whenWasYourVehicleMade: "2018",
      phoneNumber: "555-4321",
      name: "Alice Johnson",
      addEmail1: "alice.j.alt@example.com",
      quote: "Basic Plan",
      deposit: "500",
      dateOfBirth1: "1990-02-15",
      childAge: "7",
      howMuchYouLikeToStartThePlan: "1000",
      howMuchAmountWantToStartWith: "5000",
      leadID: "12345",
      startDateOfCoverage: "2024-03-01",
      whattypeofStudent: "International",
      dateOfBirthOfTraveler: "2010-05-10",
      whereWouldYouBeTravellingto: "Canada",
      tripType: "Round Trip",
      typeOfInsuranceLooking: "Health Insurance",
      ageOf1stTraveler: "34",
      travelerStartDate: "2024-06-15",
      coverageYouAreLookingFor: "Comprehensive",
      howMuchCoverageIsRequired: "500000",
      tobaccoused: "No",
      whatTypeOfTermPlanAreYouLookingFor: "10-year Term",
      howDoYouConsiderYourHealth: "Good",
      howManyCriticalIllnessCoverageYouNeed: "2",
      selectTheDurationOftheCoverage: "10 years",
      enterTheAmountOfMortgageCoverageRequired: "250000",
      doYouHaveAnyMedicalIssue: "No",
      secureYourChildsFutureWithHigherEducation: "Yes",
      eligibleToGetExtra2000InGovernmentGrants: "Yes",
      depositEveryMonthTowardsYourChildEducation: "100",
      wouldYouLikeToKnowHowRESPWorks: "Yes",
      oneMillionInanRespAccountAtRetirement: "Yes",
      doYouWanToDepositMonthlyOrYearlyPremium: "Monthly",
      whatageDoYouWanttostartTheWithdrawalFrom: "65",
      areYouAnOwnerOrEmployeeOfTheBusiness: "Owner",
      areYouLookingForDrugAndDentalOrJustDrugPla: "Both",
      totalDependents: "2",
      dependentAge1: "7",
      dependentAge3: "4",
      whatPolicyDoYouWant: "Health and Dental",
      enterageof2ndTraveler: "4",
      travelerEndDate: "2024-07-01",
      preExistingmedicaLconditions: "None",
      canYouPleaseLetMeKnowPremiumPaymentMode: "Monthly",
      doYouWantCriticalIllnessInsuranceWithMoney: "Yes",
      whatYourProfession: "Engineer",
      howMuchMonthlyBenefitDoYouNeed: "2000",
      youAreSeekingCoverageFor: "Family",
      whatsYourAge: "34",
      howMuchDoYouWantToSaveMonthly: "200",
      wouldLikeToIncreaseMonthlyDeposits: "Yes",
      howManyChildrensDoYouHave: "2",
      whatTimeFrameYouLikeToMoveToBeaAdvisor: "3 months",
      whatIsYourResidencyStatusInCanada: "Not Resident",
      howLongDoYouNeedCoverageFor: "10 years",
      moneyRequireToCompleteYourChildEducation: "50000",
      selectYourAgeBracket: "30-40",
      howMuchdoYouWantToSaveYearly: "2400",
      whatKindOfBusinesssIsIt: "Consulting",
      tripType: "Advisor Support",
      areYouLicensedAsAnInsuranceAdvisor: "Yes",
      dependentAge4: "2",
      dependentAge5: "",
      dependentAge6: "",
      relationShipStatus: "Married",
      nameOfSpouse: "John Johnson",
      numberOfSpouse: "1",
      anniversaryDate: "2010-08-10",
      spouseDateOfBirth: "1987-03-10",
      phoneOfSpouse: "555-1234",
      emailOfSpouse: "john.johnson@example.com",
      nameOfCommonLawPartner: "",
      commonLawDateOfBirth: "",
      dependentParents: "Yes",
      numberOfDependentParents: "2",
      dependentChildren: "Yes",
      numberOfDependentChildren: "2",
      siblings: "Yes",
      numberOfSiblings: "1",
      emergencyContact: "Emily Davis",
      street: "123 Maple St",
      state: "CA",
      country: "USA",
      city: "Los Angeles",
      zipCode: "90001",
      campaignidData: "C001",
      adgroupidData: "A001",
      matchtypeData: "Exact",
      gclidData: "G12345",
      networkData: "Google",
      deviceData: "Mobile",
      keywordData: "Insurance",
      lpUrlData: "http://example.com/landing",
      adAccount: "AdAcc001",
      adAccountId: "AdAccID001",
      adCampaign: "Health Insurance Campaign",
      adCampaignId: "AdCampID001",
      facebookPage: "Facebook Health Page",
      facebookPageId: "FB001",
      costPerLead: "15",
      adSet: "AdSet001",
      adSetId: "AdSetID001",
      facebookAd: "Facebook Ad 1",
      adId: "AdID001",
      leadForm: "Lead Form 1",
      leadFormId: "LF001",
      facebookAdInformation: "High engagement",
      religion: "Christian",
      celebratedFestivals: "Christmas, Easter",
      fesival: "Christmas: 2024-12-25",
      leadManagementHistory: "Initial contact made on 2024-01-01",
      potentialBusiness: "200000",
      lifeInsurance: "Term Life",
      livingBenefits: "Critical Illness",
      servicesRequested: "Life Insurance, Investments",
      businessLiabilityInsurance: "Yes",
      immigrationServices: "Yes",
      travelInsurance: "Yes",
      autoInsurance: "No",
      homeInsurance: "Yes",
      loanProtection: "Yes",
      investments: "50000",
      groupInsurance: "Yes",
      combinationOrHybridInsurance: "Yes",
      healthAndDentalInsurance: "Yes",
    }
  ];
  