module.exports = {
    "First Name":"firstName",
    "Last Name":"lastName",
    "Email":"email",
    "Secondary Email":"secondaryEmail",
    "Currency":"currency",	
    "Exchange Rate":"exchangeRate",
    "Email Opt Out":"emailOptOut",
    "Mobile":"mobile",
    "Lead Source":"insuranceLeadSource"
};    
// module.exports = {
//     "Record Id": "recordId",
//     "Advisor Lead Name": "advisorLeadName",
//     "Advisor Lead Owner.id": "advisorLeadOwnerId",
//     "Email": "email",
//     "Secondary Email": "secondaryEmail",
//     "Created By.id": "createdById",
//     "Modified By.id": "modifiedById",
//     "Created Time": "createdTime",
//     "Modified Time": "modifiedTime",
//     "Last Activity Time": "lastActivityTime",
//     "Currency": "currency",
//     "Exchange Rate": "exchangeRate",
//     "Email Opt Out": "emailOptOut",
//     "Layout.id": "layoutId",
//     "Tag": "tag",
//     "User Modified Time": "userModifiedTime",
//     "System Modified Time": "systemModifiedTime",
//     "User Related Activity Time": "userRelatedActivityTime",
//     "System Related Activity Time": "systemRelatedActivityTime",
//     "Unsubscribed Mode": "unsubscribedMode",
//     "Unsubscribed Time": "unsubscribedTime",
//     "Record Approval Status": "recordApprovalStatus",
//     "Is Record Duplicate": "isRecordDuplicate",
//     "Advisor Lead Image": "advisorLeadImage",
//     "Mobile": "mobile",
//     "Home Phone": "homePhone",
//     "Lead Source": "leadSource",
//     "Street Address": "streetAddress",
//     "City": "city",
//     "Province": "province",
//     "Hire Level": "hireLevel",
//     "Individual - Bonus %": "individualBonus",
//     "Lead Status": "leadStatus",
//     "Team Name": "teamName",
//     "Team Leg Number": "teamLegNumber",
//     "Team Generation Number": "teamGenerationNumber",
//     "Location Assigned.id": "locationAssignedId",
//     "Advisor's Licence Expiry": "advisorLicenceExpiry",
//     "Advisor's E&O Policy Expiry": "advisorEOPolicyExpiry",
//     "Advisor's Licence Number": "advisorLicenceNumber",
//     "Advisor's E&O Policy Number": "advisorEOPolicyNumber",
//     "Advisor's Date of Hire": "advisorDateOfHire",
//     "Advisor's Date of Birth": "advisorDateOfBirth",
//     "Advisor First Name": "advisorFirstName",
//     "Postal Code": "postalCode",
//     "Desired Timeline for achieving Preferences": "desiredTimelineForAchievingPreferences",
//     "Life & Career Preferences": "lifeCareerPreferences",
//     "If Licensed, Since How Long?": "ifLicensedSinceHowLong",
//     "How long are you licensed?": "howLongAreYouLicensed",
//     "Description": "description",
//     "What are you looking for": "whatAreYouLookingFor",
//     "What is the problem are you looking to solve": "whatIsTheProblemAreYouLookingToSolve",
//     "Locked": "locked",
//     "Are you LLQP Licensed?": "areYouLLQPLicensed",
//     "Record Status": "recordStatus",
//     "Page Url": "pageUrl",
//     "Looking For Advisor?": "lookingForAdvisor",
//     "What time frame you like to move to be a advisor?": "whatTimeFrameYouLikeToMoveToBeAAdvisor",
//     "Are You Licensed as an Insurance Advisor?": "areYouLicensedAsAnInsuranceAdvisor"
// }